import { VerticalDefinition, PackageDefinition, AddonDefinition } from '../types';

export const VERTICALS: Record<string, VerticalDefinition> = {
  taxi_cab: {
    id: 'taxi_cab',
    name: 'Taxi & Cab Operations',
    description: 'Urban mobility, point-to-point dispatch, surge fare models, and driver shift optimization.',
    icon: 'Car',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    features: ['Metered Billing', 'Passenger SOS', 'Shift Roster', 'Surge Pricing'],
  },
  tourist_bus: {
    id: 'tourist_bus',
    name: 'Tourist & Commercial Bus',
    description: 'Intercity scheduled routes, seat allocations, tourist chartered tours, and luxury coach maintenance.',
    icon: 'Bus',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    features: ['Seat Allocation', 'Manifest System', 'Route Timetables', 'Charter Quotes'],
  },
  freight_logistics: {
    id: 'freight_logistics',
    name: 'Goods & Freight Logistics',
    description: 'Full truckload (FTL) and less-than-truckload (LTL) cross-country movement with weighbridge tracking.',
    icon: 'Truck',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    features: ['FTL / LTL Multi-drop', 'Weighbridge Sync', 'E-Way Bills', 'Proof of Delivery (e-POD)'],
  },
  packers_movers: {
    id: 'packers_movers',
    name: 'Packers & Movers',
    description: 'Residential & corporate relocations, box-level tagging, loading crew management, and insurance riders.',
    icon: 'Package',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    features: ['Itemized Packing Lists', 'Crew Dispatch', 'Transit Insurance', 'Damage Claims'],
  },
  b2b_contract: {
    id: 'b2b_contract',
    name: 'B2B Contract Logistics',
    description: 'Dedicated client fleets, complex SLA metrics, monthly minimum guarantees, and corporate billing.',
    icon: 'Briefcase',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    features: ['SLA Compliance Tracker', 'Minimum Guarantee Guages', 'Tender Cost Estimator', 'Milestone Billing'],
  },
  cold_chain: {
    id: 'cold_chain',
    name: 'Cold Chain & Reefer Fleet',
    description: 'Temperature & humidity telemetry for pharma, perishable foods, dairy, with automated breach alarms.',
    icon: 'Snowflake',
    badgeColor: 'bg-sky-500/20 text-sky-300 border-sky-500/30',
    features: ['Reefer Telemetry', 'Temp Breach Alarms', 'Pharma Compliance Logs', 'Multi-zone Monitoring'],
  },
  last_mile: {
    id: 'last_mile',
    name: 'E-commerce Last-Mile Delivery',
    description: 'High-density urban routing, doorstep barcode scanning, Cash-on-Delivery (COD) cash reconciliation.',
    icon: 'Navigation',
    badgeColor: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
    features: ['COD Reconciliation', 'Route Clustered Dispatch', 'Failed Delivery Rerouting', 'Driver Mobile Scanner'],
  },
  heavy_machinery: {
    id: 'heavy_machinery',
    name: 'Specialized Heavy Machinery',
    description: 'Oversized cargo (ODC), hydraulic axles, route clearance permits, and escort vehicle coordination.',
    icon: 'Wrench',
    badgeColor: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
    features: ['ODC Route Feasibility', 'Axle Weight Calculations', 'Escort Fleet Sync', 'Police Transit Permits'],
  },
  courier_express: {
    id: 'courier_express',
    name: 'Courier & Express Delivery',
    description: 'AWB lifecycle, multi-point pickups, high-speed sorting hubs, first/last-mile dispatch, PoD verification, and courier agent commissions.',
    icon: 'PackageCheck',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    features: ['AWB Tracking', 'Sorting Hubs', 'Multi-point Pickups', 'e-PoD OTP/Signature', 'Agent Commissions'],
  },
  tourist_taxi: {
    id: 'tourist_taxi',
    name: 'Tourist Taxi Operations',
    description: 'Long-distance intercity tourism, airport transfers, chauffeur packages, and multilingual itinerary billing.',
    icon: 'Car',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    features: ['Itinerary Booking', 'Airport Flight Sync', 'Chauffeur Tariffs', 'Sightseeing Manifests'],
  },
  corporate_fleet: {
    id: 'corporate_fleet',
    name: 'Corporate Fleet Operations',
    description: 'Executive mobility, dedicated enterprise pool cars, corporate expense accounts, and VIP guest dispatching.',
    icon: 'Briefcase',
    badgeColor: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
    features: ['Executive Bookings', 'Corporate Cost Centers', 'Priority Allocation', 'VIP Chauffeur Protocols'],
  },
  project_logistics: {
    id: 'project_logistics',
    name: 'Project-Based Logistics',
    description: 'Turnkey industrial EPC logistics, infrastructure supply chain, milestone movement, and dedicated project task forces.',
    icon: 'Building2',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    features: ['Project Milestones', 'Job Site Marshaling', 'Dedicated Task Forces', 'Multi-Leg Consignments'],
  },
  bulk_fleet: {
    id: 'bulk_fleet',
    name: 'Bulk Fleet Operations',
    description: 'Dry bulk, petroleum tankers, agricultural grains, cement, and chemical haulage with gross-tare weighbridge integration.',
    icon: 'Truck',
    badgeColor: 'bg-stone-500/20 text-stone-300 border-stone-500/30',
    features: ['Tare & Gross Calibration', 'Hazardous Materials (Hazmat)', 'Tanker Compartments', 'Dip Chart Sync'],
  },
  corporate_shuttle: {
    id: 'corporate_shuttle',
    name: 'School & Corporate Shuttle / Bus Pooling',
    description: 'Fixed and pooled route transit, sequential stops, employee & student rosters, RFID/QR boarding passes, and shift trip scheduling.',
    icon: 'Users',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    features: ['Fixed Route Schedules', 'Sequential Stop Timings', 'Passenger Rosters', 'Digital Attendance', 'Corporate Shift Sync'],
  },
  all_verticals: {
    id: 'all_verticals',
    name: 'Enterprise Multi-Vertical Hub',
    description: 'Conglomerates managing multi-modal fleets spanning passenger, heavy cargo, cold-chain, and urban hubs.',
    icon: 'Layers',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    features: ['Cross-Vertical Analytics', 'Unified Resource Pooling', 'Global Billing Engine', 'Corporate SLAs'],
  },
};

export const PACKAGES: Record<string, PackageDefinition> = {
  basic: {
    id: 'basic',
    name: 'Basic Starter',
    tagline: 'Core vehicles, driver rosters, basic bookings, and essential reporting.',
    monthlyPrice: 149,
    annualPrice: 1490,
    maxVehicles: 25,
    maxUsers: 5,
    coreFeatures: [
      'Vehicle & Driver Registry',
      'Basic Booking & Trip Dispatch',
      'Document Expiry Alerts',
      'Standard Financial Reports',
      'Email Support',
    ],
    recommendedFor: 'Independent fleet operators & growing local transport agencies.',
  },
  standard: {
    id: 'standard',
    name: 'Standard Fleet',
    tagline: 'Fleet operations, preventive maintenance, finance, and expanded reporting.',
    monthlyPrice: 399,
    annualPrice: 3990,
    maxVehicles: 100,
    maxUsers: 20,
    coreFeatures: [
      'All Basic features',
      'Preventive Maintenance & Workshop Schedules',
      'Fuel & Toll Expense Tracking',
      'Driver Safety & Performance Scoring',
      'Invoice Lifecycle Management',
      'Standard API Access',
    ],
    recommendedFor: 'Regional logistics providers & commercial transport firms.',
  },
  corporate: {
    id: 'corporate',
    name: 'Corporate Enterprise',
    tagline: 'Contracts, CRM pipeline, HR with payroll, multi-warehouse, and cross-department integration.',
    monthlyPrice: 899,
    annualPrice: 8990,
    maxVehicles: 500,
    maxUsers: 100,
    coreFeatures: [
      'All Standard features',
      'Contract & Tender Management with SLA Tracking',
      'Multi-Warehouse & Spare Parts Inventory',
      'CRM Sales Pipeline & Customer Portals',
      'HR Department & Driver Payroll',
      'Insurance & Legal Claim Tracking',
      'Dedicated Account Manager',
    ],
    recommendedFor: 'Large B2B contract haulers, multi-city logistics networks, & bus fleets.',
  },
  enterprise: {
    id: 'enterprise',
    name: 'OmniCore Ecosystem',
    tagline: 'Full ecosystem, advanced telematics, real-time analytics, unlimited integrations, and multi-tenant controls.',
    monthlyPrice: 1899,
    annualPrice: 18990,
    maxVehicles: 9999,
    maxUsers: 9999,
    coreFeatures: [
      'All Corporate features',
      'Real-time GPS & Cold Chain Telemetry Stream',
      'Predictive Maintenance AI Engine',
      'Custom ERP & WMS Webhooks',
      'Multi-subsidiary Tenant Consolidation',
      'Audit Trail & SOC-2 Compliance Reporting',
      '24/7 Mission-Critical SLA & Phone Support',
    ],
    recommendedFor: 'National transport conglomerates, cold-chain pharma fleets, and logistics 3PLs.',
  },
};

export const ADDONS: AddonDefinition[] = [
  {
    key: 'addon_warehouse',
    name: 'Warehouse & Spare Parts',
    description: 'Multi-location inventory, tyre wear tracking, reorder alert triggers, and purchase orders.',
    monthlyPrice: 149,
    category: 'Operations',
  },
  {
    key: 'addon_contracts',
    name: 'Contract & Tender Management',
    description: 'Tender cost estimators, digital SLA tracking, minimum guarantee billing, and renewal alerts.',
    monthlyPrice: 199,
    category: 'Operations',
  },
  {
    key: 'addon_cold_chain',
    name: 'Cold Chain & Reefer Telemetry',
    description: 'Real-time temperature and humidity tracking with instant audible breach alerts and compliance logs.',
    monthlyPrice: 249,
    requiredForVerticals: ['cold_chain'],
    category: 'Specialized',
  },
  {
    key: 'addon_last_mile',
    name: 'Last-Mile Route Optimization',
    description: 'Doorstep dispatch clustering, driver mobile barcode scanning, and cash-on-delivery reconciliation.',
    monthlyPrice: 179,
    requiredForVerticals: ['last_mile'],
    category: 'Specialized',
  },
  {
    key: 'addon_maintenance_pro',
    name: 'Advanced Fleet Maintenance Pro',
    description: 'Predictive component wear analysis, warranty claim tracking, and work order approval workflows.',
    monthlyPrice: 129,
    category: 'Operations',
  },
  {
    key: 'addon_telematics',
    name: 'GPS & Live Telematics Pack',
    description: 'OBD-II / CAN-bus streaming, geofencing, over-speed alarms, and driver harsh braking detection.',
    monthlyPrice: 219,
    category: 'Connectivity',
  },
  {
    key: 'addon_analytics',
    name: 'Advanced BI & Analytics Suite',
    description: 'Cohort fleet analysis, fuel consumption anomaly detection, and interactive pivot reporting.',
    monthlyPrice: 199,
    category: 'Intelligence',
  },
  {
    key: 'addon_integrations',
    name: 'Open API & Webhooks Engine',
    description: 'High-throughput webhooks, SAP/Oracle ERP connectors, and customs clearance integration.',
    monthlyPrice: 299,
    category: 'Connectivity',
  },
  {
    key: 'addon_partner_portal',
    name: 'Investor & Partner Portal',
    description: 'Read-only financial and asset utilization visibility for vehicle leasing partners and investors.',
    monthlyPrice: 149,
    category: 'Intelligence',
  },
];
