import {
  Tenant,
  Vehicle,
  Driver,
  Booking,
  Trip,
  Tender,
  Contract,
  MaintenanceRecord,
  SparePart,
  WarehouseLocation,
  Invoice,
  Lead,
  Customer,
  Employee,
  InsurancePolicy,
  InsuranceClaim,
  MarketingCampaign,
  NotificationItem,
  AuditLog,
  User,
  CourierShipment,
  MultiPointPickup,
  DeliveryHub,
  SortingRecord,
  CourierAgent,
  AgentCommission,
  AgentPayout,
  ShuttleRoute,
  ShuttleSchedule,
  ShuttlePassenger,
  CrossDockRecord,
  ShipmentConsolidationGroup,
  SocialPost,
  TenantPublicCms,
  TenantCustomFeatureOverride,
} from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'user_superadmin',
    email: 'admin@omnicore.io',
    firstName: 'Alexander',
    lastName: 'Vance',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isPlatformUser: true,
    platformRole: 'super_admin',
    permissions: ['*'],
    mfaEnabled: true,
    status: 'active',
  },
  {
    id: 'user_tenant_admin',
    email: 'sarang@apexlogistics.com',
    firstName: 'Marcus',
    lastName: 'Sterling',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isPlatformUser: false,
    tenantId: 'tenant_apex',
    tenantRole: 'tenant_admin',
    permissions: [
      'tenant.manage',
      'vehicle.create', 'vehicle.update', 'vehicle.delete', 'vehicle.view',
      'driver.create', 'driver.update', 'driver.view',
      'payroll.view', 'payroll.manage',
      'trip.create', 'trip.dispatch', 'trip.update', 'trip.view',
      'contract.create', 'contract.approve', 'contract.view',
      'maintenance.create', 'maintenance.manage', 'maintenance.view',
      'warehouse.manage', 'warehouse.view',
      'finance.manage', 'finance.view',
      'crm.manage', 'crm.view',
      'hr.manage', 'hr.view',
      'reports.view', 'reports.export',
      'settings.manage',
    ],
    mfaEnabled: true,
    status: 'active',
  },
  {
    id: 'user_ops_mgr',
    email: 'ops@apexlogistics.com',
    firstName: 'Elena',
    lastName: 'Rostova',
    isPlatformUser: false,
    tenantId: 'tenant_apex',
    tenantRole: 'operations_manager',
    permissions: [
      'vehicle.create', 'vehicle.update', 'vehicle.view',
      'driver.create', 'driver.update', 'driver.view',
      'trip.create', 'trip.dispatch', 'trip.update', 'trip.view',
      'maintenance.create', 'maintenance.view',
      'warehouse.view',
      'reports.view',
    ],
    mfaEnabled: false,
    status: 'active',
  },
  {
    id: 'user_finance_mgr',
    email: 'finance@apexlogistics.com',
    firstName: 'David',
    lastName: 'Chen',
    isPlatformUser: false,
    tenantId: 'tenant_apex',
    tenantRole: 'finance_user',
    permissions: [
      'finance.manage', 'finance.view',
      'payroll.view', 'payroll.manage',
      'contract.view',
      'reports.view', 'reports.export',
    ],
    mfaEnabled: true,
    status: 'active',
  },
  {
    id: 'user_driver',
    email: 'driver1@apexlogistics.com',
    firstName: 'Carlos',
    lastName: 'Mendoza',
    isPlatformUser: false,
    tenantId: 'tenant_apex',
    tenantRole: 'driver_field_user',
    permissions: [
      'trip.view',
      'vehicle.view',
    ],
    mfaEnabled: false,
    status: 'active',
  },
];

export const MOCK_TENANTS: Tenant[] = [
  {
    id: 'tenant_apex',
    name: 'Apex Global Logistics & Cold Chain',
    slug: 'apex-global',
    logo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=100&auto=format&fit=crop&q=80',
    status: 'active',
    primaryContactName: 'Marcus Sterling',
    primaryContactEmail: 'sarang@apexlogistics.com',
    primaryContactPhone: '+1 (555) 234-5678',
    country: 'United States',
    city: 'Chicago, IL',
    address: '400 N Michigan Ave, Suite 1200',
    verticals: ['freight_logistics', 'cold_chain', 'b2b_contract', 'courier_express', 'corporate_shuttle'],
    subscription: {
      package: 'enterprise',
      status: 'active',
      billingCycle: 'annually',
      startDate: '2025-01-01',
      renewalDate: '2026-12-31',
      mrr: 2148,
      currency: 'USD',
      enabledAddons: ['addon_cold_chain', 'addon_telematics', 'addon_contracts', 'addon_warehouse', 'addon_last_mile', 'addon_analytics'],
      autoRenew: true,
    },
    createdAt: '2024-03-15',
    updatedAt: '2026-09-10',
    vehicleCount: 68,
    activeTripsCount: 24,
    userCount: 42,
    storageUsedGb: 142.5,
  },
  {
    id: 'tenant_speedy_courier',
    name: 'SpeedyJet Express Delivery Services',
    slug: 'speedyjet',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    status: 'active',
    primaryContactName: 'Rachel Vance',
    primaryContactEmail: 'rachel@speedyjet.com',
    primaryContactPhone: '+1 (555) 345-9876',
    country: 'United States',
    city: 'Atlanta, GA',
    address: '100 Peachtree St NW, Suite 400',
    verticals: ['courier_express'],
    subscription: {
      package: 'corporate',
      status: 'active',
      billingCycle: 'monthly',
      startDate: '2025-04-01',
      renewalDate: '2026-10-01',
      mrr: 899,
      currency: 'USD',
      enabledAddons: ['addon_last_mile', 'addon_telematics'],
      autoRenew: true,
    },
    createdAt: '2025-04-01',
    updatedAt: '2026-09-12',
    vehicleCount: 38,
    activeTripsCount: 45,
    userCount: 22,
    storageUsedGb: 58.4,
  },
  {
    id: 'tenant_campus_shuttle',
    name: 'Horizon Campus & Corporate Transit',
    slug: 'horizon-shuttle',
    logo: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=100&auto=format&fit=crop&q=80',
    status: 'active',
    primaryContactName: 'David Sterling',
    primaryContactEmail: 'david@horizonshuttle.com',
    primaryContactPhone: '+1 (555) 456-1122',
    country: 'United States',
    city: 'Seattle, WA',
    address: '401 Terry Ave N',
    verticals: ['corporate_shuttle'],
    subscription: {
      package: 'standard',
      status: 'active',
      billingCycle: 'monthly',
      startDate: '2025-08-01',
      renewalDate: '2026-10-01',
      mrr: 399,
      currency: 'USD',
      enabledAddons: ['addon_telematics'],
      autoRenew: true,
    },
    createdAt: '2025-08-01',
    updatedAt: '2026-09-11',
    vehicleCount: 24,
    activeTripsCount: 16,
    userCount: 14,
    storageUsedGb: 31.0,
  },
  {
    id: 'tenant_metro_cabs',
    name: 'Metro City Express Mobility',
    slug: 'metro-cabs',
    status: 'active',
    primaryContactName: 'Priya Sharma',
    primaryContactEmail: 'priya@metrocabs.com',
    primaryContactPhone: '+1 (555) 876-5432',
    country: 'United States',
    city: 'Austin, TX',
    address: '800 Congress Ave',
    verticals: ['taxi_cab'],
    subscription: {
      package: 'standard',
      status: 'active',
      billingCycle: 'monthly',
      startDate: '2025-06-01',
      renewalDate: '2026-10-01',
      mrr: 399,
      currency: 'USD',
      enabledAddons: ['addon_telematics'],
      autoRenew: true,
    },
    createdAt: '2025-06-01',
    updatedAt: '2026-09-02',
    vehicleCount: 45,
    activeTripsCount: 19,
    userCount: 12,
    storageUsedGb: 38.2,
  },
  {
    id: 'tenant_summit_bus',
    name: 'Summit Intercity Coaches',
    slug: 'summit-bus',
    status: 'active',
    primaryContactName: 'Arthur Pendelton',
    primaryContactEmail: 'arthur@summitbus.com',
    primaryContactPhone: '+1 (555) 432-1098',
    country: 'Canada',
    city: 'Calgary, AB',
    address: '120 8 Ave SW',
    verticals: ['tourist_bus'],
    subscription: {
      package: 'corporate',
      status: 'active',
      billingCycle: 'annually',
      startDate: '2024-11-15',
      renewalDate: '2026-11-15',
      mrr: 899,
      currency: 'USD',
      enabledAddons: ['addon_maintenance_pro', 'addon_telematics'],
      autoRenew: true,
    },
    createdAt: '2024-11-15',
    updatedAt: '2026-08-19',
    vehicleCount: 32,
    activeTripsCount: 11,
    userCount: 28,
    storageUsedGb: 74.0,
  },
  {
    id: 'tenant_swift_dispatch',
    name: 'SwiftLast E-commerce Logistics',
    slug: 'swift-last',
    status: 'trial',
    primaryContactName: 'Liam O’Connor',
    primaryContactEmail: 'liam@swiftlast.com',
    primaryContactPhone: '+1 (555) 991-2345',
    country: 'United Kingdom',
    city: 'Manchester',
    address: '14 Oxford St',
    verticals: ['last_mile'],
    subscription: {
      package: 'standard',
      status: 'trial',
      billingCycle: 'monthly',
      startDate: '2026-09-01',
      renewalDate: '2026-10-01',
      mrr: 0,
      currency: 'USD',
      enabledAddons: ['addon_last_mile'],
      autoRenew: false,
    },
    createdAt: '2026-09-01',
    updatedAt: '2026-09-14',
    vehicleCount: 18,
    activeTripsCount: 8,
    userCount: 6,
    storageUsedGb: 12.1,
  },
  {
    id: 'tenant_titan_heavy',
    name: 'Titan Heavy Rigging & Machinery',
    slug: 'titan-heavy',
    status: 'suspended',
    primaryContactName: 'Gunnar Berg',
    primaryContactEmail: 'gunnar@titanheavy.no',
    primaryContactPhone: '+47 22 34 56 78',
    country: 'Norway',
    city: 'Stavanger',
    address: 'Strandkaien 24',
    verticals: ['heavy_machinery'],
    subscription: {
      package: 'corporate',
      status: 'past_due',
      billingCycle: 'monthly',
      startDate: '2025-02-10',
      renewalDate: '2026-08-10',
      mrr: 1098,
      currency: 'USD',
      enabledAddons: ['addon_contracts', 'addon_maintenance_pro'],
      autoRenew: false,
    },
    createdAt: '2025-02-10',
    updatedAt: '2026-09-01',
    vehicleCount: 14,
    activeTripsCount: 0,
    userCount: 9,
    storageUsedGb: 29.8,
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'veh_01',
    tenantId: 'tenant_apex',
    registrationNumber: 'IL-9428-TX',
    make: 'Volvo',
    model: 'FH16 750 Reefer',
    year: 2024,
    type: 'reefer_cold',
    vertical: 'cold_chain',
    status: 'on_trip',
    vin: 'YV2RT40A5MA109823',
    fuelType: 'diesel',
    odometerKm: 84320,
    fuelLevelPercent: 78,
    capacityKg: 24000,
    assignedDriverId: 'drv_01',
    assignedDriverName: 'Carlos Mendoza',
    currentLocation: {
      lat: 41.8781,
      lng: -87.6298,
      address: 'I-80 Westbound, Mile Marker 142, Joliet, IL',
      speedKmh: 88,
      lastUpdated: '2 mins ago',
    },
    temperatureSensor: {
      currentTempC: -19.4,
      targetTempC: -20.0,
      humidityPercent: 62,
      status: 'normal',
    },
    documents: [
      {
        id: 'doc_v1_ins',
        type: 'insurance',
        documentNumber: 'POL-ALLIANZ-88219',
        issueDate: '2025-10-01',
        expiryDate: '2026-10-01',
        isExpiringSoon: true, // expires in 15 days
        isExpired: false,
        verificationStatus: 'verified',
      },
      {
        id: 'doc_v1_fit',
        type: 'fitness_cert',
        documentNumber: 'DOT-FIT-2026-99',
        issueDate: '2026-01-10',
        expiryDate: '2027-01-10',
        isExpiringSoon: false,
        isExpired: false,
        verificationStatus: 'verified',
      },
      {
        id: 'doc_v1_tax',
        type: 'road_tax',
        documentNumber: 'IFTA-IL-4401',
        issueDate: '2026-01-01',
        expiryDate: '2026-12-31',
        isExpiringSoon: false,
        isExpired: false,
        verificationStatus: 'verified',
      },
    ],
    totalTripsCount: 142,
    lastServiceDate: '2026-08-14',
    nextServiceKm: 90000,
  },
  {
    id: 'veh_02',
    tenantId: 'tenant_apex',
    registrationNumber: 'IL-6102-FR',
    make: 'Freightliner',
    model: 'Cascadia 126 Sleeper',
    year: 2023,
    type: 'heavy_truck',
    vertical: 'freight_logistics',
    status: 'available',
    vin: '1FUJBBCK4NL892019',
    fuelType: 'diesel',
    odometerKm: 134200,
    fuelLevelPercent: 94,
    capacityKg: 30000,
    assignedDriverId: 'drv_02',
    assignedDriverName: 'Darius Jackson',
    currentLocation: {
      lat: 41.9742,
      lng: -87.9073,
      address: 'Apex Central Yard, O’Hare Hub, Des Plaines, IL',
      speedKmh: 0,
      lastUpdated: '10 mins ago',
    },
    documents: [
      {
        id: 'doc_v2_ins',
        type: 'insurance',
        documentNumber: 'POL-TRAV-99301',
        issueDate: '2025-05-15',
        expiryDate: '2026-09-20',
        isExpiringSoon: true, // expires in 4 days!
        isExpired: false,
        verificationStatus: 'verified',
      },
    ],
    totalTripsCount: 210,
    lastServiceDate: '2026-07-22',
    nextServiceKm: 140000,
  },
  {
    id: 'veh_03',
    tenantId: 'tenant_apex',
    registrationNumber: 'IN-5509-CD',
    make: 'Kenworth',
    model: 'T680 Dual-Zone Reefer',
    year: 2024,
    type: 'reefer_cold',
    vertical: 'cold_chain',
    status: 'on_trip',
    vin: '1NKDX4EX9PR723145',
    fuelType: 'diesel',
    odometerKm: 42100,
    fuelLevelPercent: 65,
    capacityKg: 22000,
    assignedDriverId: 'drv_03',
    assignedDriverName: 'Sanjay Patel',
    currentLocation: {
      lat: 39.7684,
      lng: -86.1581,
      address: 'I-65 Southbound, Indianapolis, IN',
      speedKmh: 92,
      lastUpdated: 'Just now',
    },
    temperatureSensor: {
      currentTempC: 3.8,
      targetTempC: 4.0,
      humidityPercent: 80,
      status: 'normal',
    },
    documents: [
      {
        id: 'doc_v3_ins',
        type: 'insurance',
        documentNumber: 'POL-ALLIANZ-88220',
        issueDate: '2026-02-01',
        expiryDate: '2027-02-01',
        isExpiringSoon: false,
        isExpired: false,
        verificationStatus: 'verified',
      },
    ],
    totalTripsCount: 78,
    lastServiceDate: '2026-08-30',
    nextServiceKm: 50000,
  },
  {
    id: 'veh_04',
    tenantId: 'tenant_apex',
    registrationNumber: 'WI-3211-BT',
    make: 'Mack',
    model: 'Anthem 64T',
    year: 2022,
    type: 'heavy_truck',
    vertical: 'b2b_contract',
    status: 'maintenance',
    vin: '1M2AX07C7NM048123',
    fuelType: 'diesel',
    odometerKm: 215400,
    fuelLevelPercent: 32,
    capacityKg: 28000,
    currentLocation: {
      lat: 43.0389,
      lng: -87.9065,
      address: 'Fleet Bay 4, Milwaukee Maintenance Center',
      speedKmh: 0,
      lastUpdated: '1 hr ago',
    },
    documents: [
      {
        id: 'doc_v4_ins',
        type: 'insurance',
        documentNumber: 'POL-TRAV-84910',
        issueDate: '2025-08-10',
        expiryDate: '2026-08-10',
        isExpiringSoon: false,
        isExpired: true, // EXPIRED!
        verificationStatus: 'pending',
      },
    ],
    totalTripsCount: 310,
    lastServiceDate: '2026-09-12',
  },
  {
    id: 'veh_05',
    tenantId: 'tenant_apex',
    registrationNumber: 'IL-7832-FR',
    make: 'Peterbilt',
    model: '579 Ultraloft Linehaul',
    year: 2024,
    type: 'heavy_truck',
    vertical: 'freight_logistics',
    status: 'available',
    vin: '1XP5D49X5ND918231',
    fuelType: 'diesel',
    odometerKm: 62400,
    fuelLevelPercent: 88,
    capacityKg: 32000,
    assignedDriverId: 'drv_04',
    assignedDriverName: 'Elena Rostova',
    currentLocation: {
      lat: 41.8781,
      lng: -87.6298,
      address: 'Chicago Logistics Terminal, Bay 12',
      speedKmh: 0,
      lastUpdated: '15 mins ago',
    },
    documents: [],
    totalTripsCount: 128,
    lastServiceDate: '2026-08-20',
  },
  {
    id: 'veh_06',
    tenantId: 'tenant_apex',
    registrationNumber: 'IL-4910-CC',
    make: 'Volvo',
    model: 'VNL 860 Reefer Dual-Temp',
    year: 2024,
    type: 'reefer_cold',
    vertical: 'cold_chain',
    status: 'available',
    vin: '4V4NC9EH8NN319401',
    fuelType: 'diesel',
    odometerKm: 48900,
    fuelLevelPercent: 92,
    capacityKg: 26000,
    assignedDriverId: 'drv_05',
    assignedDriverName: 'Marcus Washington',
    currentLocation: {
      lat: 41.8337,
      lng: -87.7322,
      address: 'Cicero Cold Storage Yard, Chicago, IL',
      speedKmh: 0,
      lastUpdated: '5 mins ago',
    },
    temperatureSensor: {
      currentTempC: -20.2,
      targetTempC: -20.0,
      humidityPercent: 55,
      status: 'normal',
    },
    documents: [],
    totalTripsCount: 84,
    lastServiceDate: '2026-08-15',
  },
  {
    id: 'veh_07',
    tenantId: 'tenant_apex',
    registrationNumber: 'IL-1120-CB',
    make: 'Toyota',
    model: 'Camry Hybrid Executive Cab',
    year: 2024,
    type: 'sedan',
    vertical: 'corporate_shuttle',
    status: 'available',
    vin: '4T1B11HK5PU981240',
    fuelType: 'hybrid',
    odometerKm: 22100,
    fuelLevelPercent: 96,
    capacityPersons: 4,
    assignedDriverId: 'drv_06',
    assignedDriverName: 'Amit Shah',
    currentLocation: {
      lat: 41.9742,
      lng: -87.9073,
      address: 'O’Hare International Airport T3 VIP Staging',
      speedKmh: 0,
      lastUpdated: '3 mins ago',
    },
    documents: [],
    totalTripsCount: 240,
    lastServiceDate: '2026-09-01',
  },
  {
    id: 'veh_08',
    tenantId: 'tenant_apex',
    registrationNumber: 'IL-8804-SV',
    make: 'Ford',
    model: 'Explorer XLT Shuttle',
    year: 2023,
    type: 'suv',
    vertical: 'corporate_shuttle',
    status: 'available',
    vin: '1FM5K8GC8PGA22901',
    fuelType: 'petrol',
    odometerKm: 34800,
    fuelLevelPercent: 82,
    capacityPersons: 6,
    assignedDriverId: 'drv_07',
    assignedDriverName: 'Sarah Jenkins',
    currentLocation: {
      lat: 41.8818,
      lng: -87.6231,
      address: 'Downtown Loop Executive Garage, Chicago, IL',
      speedKmh: 0,
      lastUpdated: '12 mins ago',
    },
    documents: [],
    totalTripsCount: 165,
    lastServiceDate: '2026-08-10',
  },
];

export const MOCK_DRIVERS: Driver[] = [
  {
    id: 'drv_01',
    tenantId: 'tenant_apex',
    firstName: 'Carlos',
    lastName: 'Mendoza',
    email: 'carlos.m@apexlogistics.com',
    phone: '+1 (312) 555-0192',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    licenseNumber: 'CDL-IL-99481203',
    licenseType: 'Class A CDL + Hazmat & Tanker',
    licenseExpiryDate: '2026-10-15',
    status: 'on_trip',
    assignedVehicleId: 'veh_01',
    assignedVehicleReg: 'IL-9428-TX',
    safetyScore: 98,
    totalTrips: 340,
    onTimeDeliveryRate: 99.1,
    joinedDate: '2022-04-10',
    incidentCount: 0,
    documents: [
      {
        id: 'ddoc_1',
        type: 'commercial_license',
        documentNumber: 'CDL-IL-99481203',
        issueDate: '2021-10-15',
        expiryDate: '2026-10-15',
        isExpiringSoon: true, // Expiring in 29 days!
        isExpired: false,
      },
      {
        id: 'ddoc_2',
        type: 'medical_cert',
        documentNumber: 'DOT-MED-8491',
        issueDate: '2025-09-01',
        expiryDate: '2027-09-01',
        isExpiringSoon: false,
        isExpired: false,
      },
    ],
    payroll: {
      baseSalary: 6200,
      perTripAllowance: 380,
      overtimeRate: 45,
      bonuses: 850,
      deductions: 420,
      bankAccountNumber: '•••• •••• 4910',
      bankName: 'JPMorgan Chase Bank',
      taxId: 'SSN •••-••-9182',
      lastPayoutDate: '2026-08-31',
    },
  },
  {
    id: 'drv_02',
    tenantId: 'tenant_apex',
    firstName: 'Darius',
    lastName: 'Jackson',
    email: 'darius.j@apexlogistics.com',
    phone: '+1 (312) 555-0834',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    licenseNumber: 'CDL-IL-77291044',
    licenseType: 'Class A CDL',
    licenseExpiryDate: '2027-08-20',
    status: 'available',
    assignedVehicleId: 'veh_02',
    assignedVehicleReg: 'IL-6102-FR',
    safetyScore: 94,
    totalTrips: 215,
    onTimeDeliveryRate: 97.4,
    joinedDate: '2023-01-15',
    incidentCount: 1,
    documents: [
      {
        id: 'ddoc_3',
        type: 'commercial_license',
        documentNumber: 'CDL-IL-77291044',
        issueDate: '2022-08-20',
        expiryDate: '2027-08-20',
        isExpiringSoon: false,
        isExpired: false,
      },
    ],
    payroll: {
      baseSalary: 5600,
      perTripAllowance: 320,
      overtimeRate: 40,
      bonuses: 400,
      deductions: 350,
      bankAccountNumber: '•••• •••• 1184',
      bankName: 'Bank of America',
      taxId: 'SSN •••-••-4421',
      lastPayoutDate: '2026-08-31',
    },
  },
  {
    id: 'drv_03',
    tenantId: 'tenant_apex',
    firstName: 'Sanjay',
    lastName: 'Patel',
    email: 'sanjay.p@apexlogistics.com',
    phone: '+1 (317) 555-9128',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    licenseNumber: 'CDL-IN-48291029',
    licenseType: 'Class A CDL + Reefer Endorsement',
    licenseExpiryDate: '2026-09-25',
    status: 'on_trip',
    assignedVehicleId: 'veh_03',
    assignedVehicleReg: 'IN-5509-CD',
    safetyScore: 99,
    totalTrips: 410,
    onTimeDeliveryRate: 99.8,
    joinedDate: '2021-08-01',
    incidentCount: 0,
    documents: [
      {
        id: 'ddoc_4',
        type: 'commercial_license',
        documentNumber: 'CDL-IN-48291029',
        issueDate: '2021-09-25',
        expiryDate: '2026-09-25',
        isExpiringSoon: true, // 9 days left!
        isExpired: false,
      },
    ],
    payroll: {
      baseSalary: 6500,
      perTripAllowance: 410,
      overtimeRate: 48,
      bonuses: 950,
      deductions: 480,
      bankAccountNumber: '•••• •••• 8823',
      bankName: 'Wells Fargo',
      taxId: 'SSN •••-••-7703',
      lastPayoutDate: '2026-08-31',
    },
  },
  {
    id: 'drv_04',
    tenantId: 'tenant_apex',
    firstName: 'Elena',
    lastName: 'Rostova',
    email: 'elena.r@apexlogistics.com',
    phone: '+1 (312) 555-0482',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    licenseNumber: 'CDL-IL-88401923',
    licenseType: 'Class A CDL',
    licenseExpiryDate: '2028-05-12',
    status: 'available',
    assignedVehicleId: 'veh_05',
    assignedVehicleReg: 'IL-7832-FR',
    safetyScore: 97,
    totalTrips: 180,
    onTimeDeliveryRate: 98.8,
    joinedDate: '2023-04-20',
    incidentCount: 0,
    documents: [],
    payroll: {
      baseSalary: 5800,
      perTripAllowance: 340,
      overtimeRate: 42,
      bonuses: 500,
      deductions: 320,
      bankAccountNumber: '•••• •••• 3391',
      bankName: 'Chase Bank',
      taxId: 'SSN •••-••-5591',
      lastPayoutDate: '2026-08-31',
    },
  },
  {
    id: 'drv_05',
    tenantId: 'tenant_apex',
    firstName: 'Marcus',
    lastName: 'Washington',
    email: 'marcus.w@apexlogistics.com',
    phone: '+1 (773) 555-8831',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    licenseNumber: 'CDL-IL-33910482',
    licenseType: 'Class A CDL + Hazmat & Tanker',
    licenseExpiryDate: '2027-11-30',
    status: 'available',
    assignedVehicleId: 'veh_06',
    assignedVehicleReg: 'IL-4910-CC',
    safetyScore: 96,
    totalTrips: 290,
    onTimeDeliveryRate: 99.0,
    joinedDate: '2022-09-10',
    incidentCount: 0,
    documents: [],
    payroll: {
      baseSalary: 6100,
      perTripAllowance: 370,
      overtimeRate: 44,
      bonuses: 700,
      deductions: 380,
      bankAccountNumber: '•••• •••• 7741',
      bankName: 'Citibank',
      taxId: 'SSN •••-••-2219',
      lastPayoutDate: '2026-08-31',
    },
  },
  {
    id: 'drv_06',
    tenantId: 'tenant_apex',
    firstName: 'Amit',
    lastName: 'Shah',
    email: 'amit.s@apexlogistics.com',
    phone: '+1 (312) 555-4491',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    licenseNumber: 'CHAUFF-IL-491028',
    licenseType: 'Class D Chauffeur / Passenger Endorsement',
    licenseExpiryDate: '2028-02-14',
    status: 'available',
    assignedVehicleId: 'veh_07',
    assignedVehicleReg: 'IL-1120-CB',
    safetyScore: 99,
    totalTrips: 450,
    onTimeDeliveryRate: 99.4,
    joinedDate: '2021-11-05',
    incidentCount: 0,
    documents: [],
    payroll: {
      baseSalary: 4900,
      perTripAllowance: 220,
      overtimeRate: 35,
      bonuses: 450,
      deductions: 280,
      bankAccountNumber: '•••• •••• 9901',
      bankName: 'US Bank',
      taxId: 'SSN •••-••-8812',
      lastPayoutDate: '2026-08-31',
    },
  },
  {
    id: 'drv_07',
    tenantId: 'tenant_apex',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    email: 'sarah.j@apexlogistics.com',
    phone: '+1 (773) 555-1289',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    licenseNumber: 'CHAUFF-IL-772910',
    licenseType: 'Class D Chauffeur / Commercial Passenger',
    licenseExpiryDate: '2027-06-20',
    status: 'available',
    assignedVehicleId: 'veh_08',
    assignedVehicleReg: 'IL-8804-SV',
    safetyScore: 98,
    totalTrips: 310,
    onTimeDeliveryRate: 98.7,
    joinedDate: '2022-07-18',
    incidentCount: 0,
    documents: [],
    payroll: {
      baseSalary: 5100,
      perTripAllowance: 240,
      overtimeRate: 36,
      bonuses: 500,
      deductions: 300,
      bankAccountNumber: '•••• •••• 4429',
      bankName: 'PNC Bank',
      taxId: 'SSN •••-••-9930',
      lastPayoutDate: '2026-08-31',
    },
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk_01',
    bookingCode: 'BK-2026-901',
    tenantId: 'tenant_apex',
    customerName: 'Pfizer BioPharma North America',
    customerPhone: '+1 (800) 555-0199',
    customerEmail: 'logistics@pfizer.com',
    vertical: 'cold_chain',
    vehicleType: 'reefer_cold',
    pickupLocation: 'Pfizer Distribution Facility, Kalamazoo, MI',
    dropoffLocation: 'Northwestern Memorial Hospital Hub, Chicago, IL',
    scheduledPickupTime: '2026-09-17 08:00',
    cargoDescription: '22 Pallets Temperature-Sensitive Vaccines (-20°C strictly mandated)',
    estimatedWeightKg: 8400,
    estimatedAmount: 3850,
    currency: 'USD',
    status: 'confirmed',
    createdAt: '2026-09-16 10:14',
  },
  {
    id: 'bk_02',
    bookingCode: 'BK-2026-902',
    tenantId: 'tenant_apex',
    customerName: 'Target Logistics Regional DC',
    customerPhone: '+1 (888) 555-9482',
    customerEmail: 'inbound@target.com',
    vertical: 'freight_logistics',
    vehicleType: 'heavy_truck',
    pickupLocation: 'Target DC #48, Gary, IN',
    dropoffLocation: 'Target Distribution Center, Rockford, IL',
    scheduledPickupTime: '2026-09-17 14:30',
    cargoDescription: 'Full Truckload Consumer Electronics & Dry Packets',
    estimatedWeightKg: 19500,
    estimatedAmount: 2400,
    currency: 'USD',
    status: 'pending',
    createdAt: '2026-09-16 14:20',
  },
  {
    id: 'bk_03',
    bookingCode: 'BK-2026-903',
    tenantId: 'tenant_apex',
    customerName: 'John Deere Industrial Parts',
    customerPhone: '+1 (800) 555-3211',
    customerEmail: 'freight@johndeere.com',
    vertical: 'b2b_contract',
    vehicleType: 'heavy_truck',
    pickupLocation: 'John Deere Works, Moline, IL',
    dropoffLocation: 'Assembly Plant 3, Fort Wayne, IN',
    scheduledPickupTime: '2026-09-18 06:00',
    cargoDescription: 'Heavy Transmission Modules & Axle Assemblies',
    estimatedWeightKg: 24500,
    estimatedAmount: 4200,
    currency: 'USD',
    status: 'pending',
    createdAt: '2026-09-16 16:45',
  },
  {
    id: 'bk_04',
    bookingCode: 'BK-2026-904',
    tenantId: 'tenant_apex',
    customerName: 'Deloitte Consulting Partner Chauffeur',
    customerPhone: '+1 (312) 555-8800',
    customerEmail: 'travel@deloitte.com',
    vertical: 'corporate_shuttle',
    vehicleType: 'sedan',
    passengerCount: 3,
    pickupLocation: 'O’Hare International Terminal 5 Arrivals',
    dropoffLocation: 'The Ritz-Carlton, Water Tower Place, Chicago',
    scheduledPickupTime: '2026-09-17 18:00',
    cargoDescription: 'Executive Airport Sedan Transfer with 4 Luxury Luggage bags',
    estimatedAmount: 480,
    currency: 'USD',
    status: 'pending',
    createdAt: '2026-09-17 09:30',
  },
];

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip_101',
    tripCode: 'TRP-2026-8801',
    tenantId: 'tenant_apex',
    bookingId: 'bk_00',
    customerName: 'Abbott Diagnostics',
    vertical: 'cold_chain',
    vehicleId: 'veh_01',
    vehicleReg: 'IL-9428-TX',
    driverId: 'drv_01',
    driverName: 'Carlos Mendoza',
    driverPhone: '+1 (312) 555-0192',
    origin: 'Abbott Park, North Chicago, IL',
    destination: 'Barnes-Jewish Hospital, St. Louis, MO',
    distanceKm: 520,
    status: 'in_transit',
    startTime: '2026-09-16 06:30',
    estimatedArrival: '2026-09-16 14:00',
    commercialRate: 4100,
    expensesTotal: 345,
    expenses: [
      {
        id: 'exp_1',
        tripId: 'trip_101',
        category: 'fuel',
        amount: 280,
        currency: 'USD',
        loggedAt: '2026-09-16 09:15',
        approved: true,
      },
      {
        id: 'exp_2',
        tripId: 'trip_101',
        category: 'toll',
        amount: 65,
        currency: 'USD',
        loggedAt: '2026-09-16 10:40',
        approved: true,
      },
    ],
    temperatureLogs: [
      { timestamp: '07:00', tempC: -19.8 },
      { timestamp: '08:00', tempC: -19.5 },
      { timestamp: '09:00', tempC: -19.4 },
      { timestamp: '10:00', tempC: -19.2 },
    ],
    timeline: [
      { status: 'scheduled', timestamp: '2026-09-15 16:00', note: 'Trip planned & assigned to Volvo FH16' },
      { status: 'dispatched', timestamp: '2026-09-16 05:45', note: 'Driver Carlos Mendoza acknowledged manifest' },
      { status: 'loading', timestamp: '2026-09-16 06:00', note: 'Pre-cooling verified at -20°C. 18 pallets loaded' },
      { status: 'started', timestamp: '2026-09-16 06:30', note: 'Departed Abbott Park hub' },
      { status: 'in_transit', timestamp: '2026-09-16 09:30', note: 'Passing Bloomington, IL. Temp steady at -19.4°C' },
    ],
  },
  {
    id: 'trip_102',
    tripCode: 'TRP-2026-8802',
    tenantId: 'tenant_apex',
    customerName: 'Eli Lilly & Company',
    vertical: 'cold_chain',
    vehicleId: 'veh_03',
    vehicleReg: 'IN-5509-CD',
    driverId: 'drv_03',
    driverName: 'Sanjay Patel',
    driverPhone: '+1 (317) 555-9128',
    origin: 'Lilly Corporate Center, Indianapolis, IN',
    destination: 'Midwest Regional Vaccine Depository, Columbus, OH',
    distanceKm: 285,
    status: 'in_transit',
    startTime: '2026-09-16 08:15',
    estimatedArrival: '2026-09-16 13:00',
    commercialRate: 2950,
    expensesTotal: 185,
    expenses: [
      {
        id: 'exp_3',
        tripId: 'trip_102',
        category: 'fuel',
        amount: 185,
        currency: 'USD',
        loggedAt: '2026-09-16 08:30',
        approved: true,
      },
    ],
    timeline: [
      { status: 'dispatched', timestamp: '2026-09-16 07:30', note: 'Route cleared and GPS geofence established' },
      { status: 'started', timestamp: '2026-09-16 08:15', note: 'En route I-70 East' },
    ],
  },
  {
    id: 'trip_103',
    tripCode: 'TRP-2026-8798',
    tenantId: 'tenant_apex',
    customerName: 'Caterpillar Inc.',
    vertical: 'freight_logistics',
    vehicleId: 'veh_02',
    vehicleReg: 'IL-6102-FR',
    driverId: 'drv_02',
    driverName: 'Darius Jackson',
    driverPhone: '+1 (312) 555-0834',
    origin: 'Caterpillar Logistics Center, Morton, IL',
    destination: 'Detroit Engine Assembly, Detroit, MI',
    distanceKm: 610,
    status: 'completed',
    startTime: '2026-09-15 05:00',
    endTime: '2026-09-15 15:30',
    estimatedArrival: '2026-09-15 15:00',
    commercialRate: 4650,
    expensesTotal: 490,
    expenses: [],
    timeline: [
      { status: 'started', timestamp: '2026-09-15 05:00' },
      { status: 'completed', timestamp: '2026-09-15 15:30', note: 'Signed e-POD uploaded and verified' },
    ],
  },
];

export const MOCK_TENDERS: Tender[] = [
  {
    id: 'tnd_01',
    tenderCode: 'TND-2026-USPS-04',
    title: 'Midwest Inter-Facility Highway Contract Delivery 2027-2030',
    clientName: 'United States Postal Service',
    industry: 'Postal & Parcel Freight',
    estimatedValue: 2450000,
    submissionDeadline: '2026-10-10',
    status: 'under_review',
    scopeSummary: 'Daily dedicated haulage between Chicago NDC and Detroit P&DC, operating 12 dedicated tractor trailers.',
    estimatedVehicleRequired: 12,
    costBreakdown: {
      fleetCosts: 950000,
      fuelEstimates: 540000,
      crewPayroll: 620000,
      margins: 340000,
    },
  },
  {
    id: 'tnd_02',
    tenderCode: 'TND-2026-MODERNA-01',
    title: 'Ultra-Low Temperature (-70°C & -20°C) Regional Vaccine Transport',
    clientName: 'Moderna BioTherapeutics',
    industry: 'Pharmaceuticals',
    estimatedValue: 1850000,
    submissionDeadline: '2026-10-25',
    status: 'submitted',
    scopeSummary: 'Zero-breach cold chain logistics with continuous dual-satellite telemetry and certified pharma drivers.',
    estimatedVehicleRequired: 8,
    costBreakdown: {
      fleetCosts: 780000,
      fuelEstimates: 320000,
      crewPayroll: 450000,
      margins: 300000,
    },
  },
];

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'cnt_01',
    contractCode: 'CNT-PFIZER-2025',
    title: 'Pfizer BioPharma Dedicated Cold Haulage SLA',
    clientName: 'Pfizer BioPharma North America',
    vertical: 'cold_chain',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    totalContractValue: 3200000,
    realizedRevenue: 2680000,
    dedicatedVehiclesCount: 16,
    status: 'active',
    slaTargetPercent: 99.5,
    slaActualPercent: 99.8,
    paymentTerms: 'Net 30 Days',
    renewalAlertDays: 90,
  },
  {
    id: 'cnt_02',
    contractCode: 'CNT-CAT-2024',
    title: 'Caterpillar Heavy Components Dedicated Haul',
    clientName: 'Caterpillar Inc.',
    vertical: 'freight_logistics',
    startDate: '2024-06-01',
    endDate: '2026-10-31',
    totalContractValue: 1950000,
    realizedRevenue: 1820000,
    dedicatedVehiclesCount: 8,
    status: 'expiring_soon',
    slaTargetPercent: 98.0,
    slaActualPercent: 98.4,
    paymentTerms: 'Net 45 Days',
    renewalAlertDays: 45,
  },
];

export const MOCK_MAINTENANCE: MaintenanceRecord[] = [
  {
    id: 'maint_01',
    recordCode: 'WO-2026-441',
    vehicleId: 'veh_04',
    vehicleReg: 'WI-3211-BT',
    type: 'breakdown',
    status: 'in_progress',
    reportedDate: '2026-09-15',
    odometerAtService: 215400,
    workshopName: 'Apex Central Workshop, Milwaukee',
    technicianName: 'Travis Becker (Master Mechanic)',
    issueDescription: 'Turbocharger boost pressure loss on steep gradients and oil leak from intercooler pipe.',
    actionTaken: 'Turbocharger replaced with OEM Garrett unit; intercooler hose clamps torqued; oil line flushed.',
    partsConsumed: [
      {
        partId: 'prt_01',
        partName: 'Garrett Heavy Duty Turbocharger',
        partNumber: 'GAR-88401',
        quantity: 1,
        unitCost: 1450,
      },
      {
        partId: 'prt_02',
        partName: 'Synthetic Heavy Duty Engine Oil (15W-40)',
        partNumber: 'MOBIL-DELVAC-1',
        quantity: 36,
        unitCost: 18,
      },
    ],
    laborCost: 450,
    totalCost: 2548,
  },
  {
    id: 'maint_02',
    recordCode: 'WO-2026-439',
    vehicleId: 'veh_01',
    vehicleReg: 'IL-9428-TX',
    type: 'preventive',
    status: 'completed',
    reportedDate: '2026-08-14',
    completedDate: '2026-08-14',
    odometerAtService: 80000,
    workshopName: 'Thermo King Certified Service Center, Chicago',
    technicianName: 'Arthur Dent',
    issueDescription: 'Scheduled 80k Reefer Unit Maintenance and refrigerant pressure check.',
    actionTaken: 'Refrigerant R-452A recharged, compressor belt replaced, sensor calibration certified.',
    partsConsumed: [
      {
        partId: 'prt_03',
        partName: 'Thermo King Reefer Belt Kit',
        partNumber: 'TK-BELT-900',
        quantity: 1,
        unitCost: 180,
      },
    ],
    laborCost: 220,
    totalCost: 400,
  },
];

export const MOCK_WAREHOUSES: WarehouseLocation[] = [
  {
    id: 'wh_01',
    name: 'Apex Central Distribution Hub & Depot',
    code: 'ORD-WH-01',
    city: 'Chicago, IL',
    address: '9200 W Bryn Mawr Ave, Rosemont',
    capacityUnits: 15000,
    utilizedUnits: 11400,
    managerName: 'Victor Cruz',
  },
  {
    id: 'wh_02',
    name: 'Indianapolis Cold Storage & Transit Crossdock',
    code: 'IND-COLD-02',
    city: 'Indianapolis, IN',
    address: '4200 S High School Rd',
    capacityUnits: 8000,
    utilizedUnits: 6800,
    managerName: 'Sarah Jenkins',
  },
];

export const MOCK_SPARE_PARTS: SparePart[] = [
  {
    id: 'prt_01',
    sku: 'TYR-MICH-295-80',
    name: 'Michelin X MultiWay 3D Heavy Truck Tyre (295/80 R22.5)',
    category: 'tyres',
    warehouseId: 'wh_01',
    warehouseName: 'Apex Central Distribution Hub',
    availableQuantity: 4, // LOW STOCK!
    minQuantity: 12,
    reorderLevel: 8,
    unitCost: 420,
    sellingPrice: 560,
    locationBin: 'RACK-TYRE-A3',
    supplierName: 'Michelin Commercial Fleet Direct',
    isLowStock: true,
  },
  {
    id: 'prt_02',
    sku: 'FLT-FLEET-FS19764',
    name: 'Fleetguard Fuel Water Separator Filter',
    category: 'filters',
    warehouseId: 'wh_01',
    warehouseName: 'Apex Central Distribution Hub',
    availableQuantity: 48,
    minQuantity: 20,
    reorderLevel: 25,
    unitCost: 34,
    sellingPrice: 52,
    locationBin: 'BIN-FLT-14B',
    supplierName: 'Cummins Filtration Partners',
    isLowStock: false,
  },
  {
    id: 'prt_03',
    sku: 'BRK-BENDIX-K070796',
    name: 'Bendix ADB22X Air Disc Brake Pad Kit',
    category: 'brakes',
    warehouseId: 'wh_01',
    warehouseName: 'Apex Central Distribution Hub',
    availableQuantity: 3, // LOW STOCK!
    minQuantity: 10,
    reorderLevel: 6,
    unitCost: 165,
    sellingPrice: 240,
    locationBin: 'RACK-BRK-C1',
    supplierName: 'Bendix Commercial Vehicle Systems',
    isLowStock: true,
  },
  {
    id: 'prt_04',
    sku: 'OIL-MOBIL-DELVAC-1',
    name: 'Mobil Delvac 1 ESP 5W-40 Synthetic Oil (55 Gal Drum)',
    category: 'lubricants',
    warehouseId: 'wh_02',
    warehouseName: 'Indianapolis Cold Storage Crossdock',
    availableQuantity: 6,
    minQuantity: 4,
    reorderLevel: 5,
    unitCost: 890,
    sellingPrice: 1150,
    locationBin: 'HAZMAT-DRUM-02',
    supplierName: 'ExxonMobil Commercial',
    isLowStock: false,
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv_01',
    invoiceNumber: 'INV-2026-0891',
    clientName: 'Pfizer BioPharma North America',
    issueDate: '2026-09-01',
    dueDate: '2026-10-01',
    amount: 142500,
    taxAmount: 11400,
    totalAmount: 153900,
    balanceDue: 153900,
    status: 'issued',
    vertical: 'cold_chain',
    items: [
      { description: 'August Dedicated Cold-Chain Linehaul Services (16 Reefers)', quantity: 1, unitPrice: 142500, total: 142500 },
    ],
  },
  {
    id: 'inv_02',
    invoiceNumber: 'INV-2026-0870',
    clientName: 'Target Logistics Regional DC',
    issueDate: '2026-08-15',
    dueDate: '2026-09-15',
    amount: 68400,
    taxAmount: 5472,
    totalAmount: 73872,
    balanceDue: 73872,
    status: 'overdue',
    vertical: 'freight_logistics',
    items: [
      { description: 'Midwest Regional FTL Freight Movements (38 Trips)', quantity: 38, unitPrice: 1800, total: 68400 },
    ],
  },
  {
    id: 'inv_03',
    invoiceNumber: 'INV-2026-0855',
    clientName: 'Caterpillar Inc.',
    issueDate: '2026-08-01',
    dueDate: '2026-09-01',
    amount: 94000,
    taxAmount: 7520,
    totalAmount: 101520,
    balanceDue: 0,
    status: 'paid',
    vertical: 'b2b_contract',
    items: [
      { description: 'Heavy Component Haulage Contract - July Billing', quantity: 1, unitPrice: 94000, total: 94000 },
    ],
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead_01',
    companyName: 'Merck Animal Health & Pharma',
    contactPerson: 'Dr. Gregory House',
    email: 'ghouse@merck.com',
    phone: '+1 (908) 555-4920',
    stage: 'proposal',
    verticalInterest: 'cold_chain',
    estimatedMonthlyValue: 85000,
    assignedRep: 'Sarah Sterling (Commercial VP)',
    notes: 'Needs 8 dedicated reefers with continuous calibration for biologics distribution across the Midwest.',
    lastContactDate: '2026-09-14',
  },
  {
    id: 'lead_02',
    companyName: 'Amazon Freight Partner Network',
    contactPerson: 'Rachel Zane',
    email: 'rzane@amazon.com',
    phone: '+1 (206) 555-1928',
    stage: 'negotiation',
    verticalInterest: 'last_mile',
    estimatedMonthlyValue: 140000,
    assignedRep: 'David Chen',
    notes: 'Reviewing cross-dock terminal throughput and delivery success SLA guarantees.',
    lastContactDate: '2026-09-15',
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust_01',
    name: 'Pfizer BioPharma North America',
    code: 'CUST-PFZ-01',
    contactPerson: 'Michael Chang',
    email: 'logistics@pfizer.com',
    phone: '+1 (800) 555-0199',
    address: '66 Hudson Blvd E, New York, NY 10001',
    taxNumber: 'US-13-281904',
    creditLimit: 500000,
    outstandingBalance: 153900,
    activeContractsCount: 2,
    totalTripsCompleted: 840,
  },
  {
    id: 'cust_02',
    name: 'Caterpillar Inc.',
    code: 'CUST-CAT-02',
    contactPerson: 'Douglas Vance',
    email: 'freight@cat.com',
    phone: '+1 (309) 675-1000',
    address: '510 Lake Cook Rd, Deerfield, IL 60015',
    taxNumber: 'US-37-024090',
    creditLimit: 350000,
    outstandingBalance: 0,
    activeContractsCount: 1,
    totalTripsCompleted: 620,
  },
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'emp_01',
    employeeCode: 'EMP-010',
    firstName: 'Marcus',
    lastName: 'Sterling',
    email: 'sarang@apexlogistics.com',
    phone: '+1 (312) 555-1200',
    department: 'Admin',
    role: 'tenant_admin',
    joiningDate: '2020-03-01',
    status: 'active',
    salary: {
      monthlyBasic: 12500,
      allowances: 2500,
      deductions: 2800,
      netPay: 12200,
    },
  },
  {
    id: 'emp_02',
    employeeCode: 'EMP-024',
    firstName: 'Elena',
    lastName: 'Rostova',
    email: 'ops@apexlogistics.com',
    phone: '+1 (312) 555-1205',
    department: 'Operations',
    role: 'operations_manager',
    joiningDate: '2021-06-15',
    status: 'active',
    salary: {
      monthlyBasic: 8500,
      allowances: 1200,
      deductions: 1900,
      netPay: 7800,
    },
  },
];

export const MOCK_INSURANCE: InsurancePolicy[] = [
  {
    id: 'ins_pol_01',
    policyNumber: 'POL-ALLIANZ-88219',
    provider: 'Allianz Global Corporate & Specialty',
    type: 'fleet_comprehensive',
    coverageAmount: 15000000,
    premiumAmount: 84000,
    startDate: '2025-10-01',
    expiryDate: '2026-10-01',
    status: 'expiring_soon',
    coveredVehiclesCount: 42,
  },
  {
    id: 'ins_pol_02',
    policyNumber: 'POL-CHUBB-COLD-90',
    provider: 'Chubb In-Transit Cargo Insurance',
    type: 'cold_spoilage_cover',
    coverageAmount: 8000000,
    premiumAmount: 42000,
    startDate: '2026-01-01',
    expiryDate: '2027-01-01',
    status: 'active',
    coveredVehiclesCount: 26,
  },
];

export const MOCK_CLAIMS: InsuranceClaim[] = [
  {
    id: 'clm_01',
    claimNumber: 'CLM-2026-019',
    policyNumber: 'POL-ALLIANZ-88219',
    vehicleReg: 'WI-3211-BT',
    incidentDate: '2026-08-28',
    claimAmount: 4800,
    settledAmount: 4200,
    status: 'settled',
    description: 'Minor bumper and step damage from low speed loading dock contact in heavy fog.',
  },
];

export const MOCK_CAMPAIGNS: MarketingCampaign[] = [
  {
    id: 'cmp_01',
    name: 'Midwest Pharma Cold Chain Blitz Q3',
    channel: 'LinkedIn B2B',
    verticalTarget: 'cold_chain',
    budget: 18000,
    spend: 14200,
    leadsGenerated: 34,
    conversions: 6,
    cac: 2366,
    roi: 480,
    status: 'active',
  },
  {
    id: 'cmp_02',
    name: 'Heavy Haulage Energy & Infrastructure Expo',
    channel: 'Industry Expo',
    verticalTarget: 'heavy_machinery',
    budget: 25000,
    spend: 25000,
    leadsGenerated: 21,
    conversions: 4,
    cac: 6250,
    roi: 320,
    status: 'completed',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    type: 'vehicle_document_expiry',
    title: 'Vehicle Insurance Expiring Soon',
    message: 'Volvo FH16 (IL-9428-TX) Allianz policy expires in 15 days on Oct 1, 2026.',
    severity: 'high',
    timestamp: '15 mins ago',
    isRead: false,
    linkUrl: '/app/fleet',
    actionRequired: true,
  },
  {
    id: 'notif_02',
    type: 'driver_license_expiry',
    title: 'Driver CDL Renewal Due',
    message: 'Sanjay Patel commercial license expires in 9 days (Sep 25, 2026). Action required to prevent grounding.',
    severity: 'critical',
    timestamp: '1 hour ago',
    isRead: false,
    linkUrl: '/app/drivers',
    actionRequired: true,
  },
  {
    id: 'notif_03',
    type: 'low_inventory',
    title: 'Critical Spare Parts Low Stock',
    message: 'Michelin Heavy Truck Tyres down to 4 units (reorder threshold is 8 units).',
    severity: 'medium',
    timestamp: '3 hours ago',
    isRead: false,
    linkUrl: '/app/warehouse',
    actionRequired: true,
  },
  {
    id: 'notif_04',
    type: 'payment_due',
    title: 'Invoice Overdue Notification',
    message: 'Target Logistics Invoice INV-2026-0870 ($73,872) is now 1 day overdue.',
    severity: 'high',
    timestamp: '5 hours ago',
    isRead: true,
    linkUrl: '/app/finance',
  },
  {
    id: 'notif_05',
    type: 'maintenance_due',
    title: 'Work Order In Progress',
    message: 'Mack Anthem 64T (WI-3211-BT) turbocharger replacement underway at Milwaukee workshop.',
    severity: 'low',
    timestamp: 'Yesterday',
    isRead: true,
    linkUrl: '/app/maintenance',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit_01',
    timestamp: '2026-09-16 14:10:22',
    tenantId: 'tenant_apex',
    tenantName: 'Apex Global Logistics & Cold Chain',
    actorEmail: 'sarang@apexlogistics.com',
    actorRole: 'Tenant Admin',
    action: 'TRIP_DISPATCHED',
    category: 'fleet',
    details: 'Dispatched trip TRP-2026-8802 with vehicle IN-5509-CD to driver Sanjay Patel',
    ipAddress: '198.51.100.44',
  },
  {
    id: 'audit_02',
    timestamp: '2026-09-16 11:24:08',
    tenantId: 'tenant_apex',
    tenantName: 'Apex Global Logistics & Cold Chain',
    actorEmail: 'finance@apexlogistics.com',
    actorRole: 'Finance User',
    action: 'INVOICE_ISSUED',
    category: 'financial',
    details: 'Generated and transmitted invoice INV-2026-0891 ($153,900.00) to Pfizer BioPharma',
    ipAddress: '198.51.100.44',
  },
  {
    id: 'audit_03',
    timestamp: '2026-09-15 09:33:14',
    tenantId: 'tenant_apex',
    tenantName: 'Apex Global Logistics & Cold Chain',
    actorEmail: 'admin@omnicore.io',
    actorRole: 'Super Admin',
    action: 'ADDON_ENABLED',
    category: 'provisioning',
    details: 'Provisioned add-on "addon_cold_chain" for tenant Apex Global Logistics',
    ipAddress: '203.0.113.19',
  },
];

// ============================================================
// COURIER & EXPRESS DELIVERY SERVICES MOCK DATA
// ============================================================
export const MOCK_COURIER_SHIPMENTS: CourierShipment[] = [
  {
    id: 'shp_01',
    awbNumber: 'AWB-EXP-88910',
    trackingNumber: 'TRK-88910-US',
    tenantId: 'tenant_apex',
    sender: {
      name: 'OmniTech Components LLC',
      phone: '+1 (312) 555-0144',
      email: 'shipping@omnitech.io',
      address: '1400 Industrial Parkway, Dock 4',
      city: 'Chicago',
      postalCode: '60607',
    },
    receiver: {
      name: 'North Shore Medical Devices',
      phone: '+1 (847) 555-9082',
      email: 'receiving@northshoremed.com',
      address: '220 Lake Cook Rd, Suite 300',
      city: 'Deerfield',
      postalCode: '60015',
    },
    parcel: {
      weightKg: 4.8,
      lengthCm: 35,
      widthCm: 25,
      heightCm: 15,
      declaredValue: 1250,
      description: 'Precision Diagnostic Sensors (Fragile Calibration)',
      isFragile: true,
    },
    serviceType: 'next_day_express',
    currentHubId: 'hub_chi_01',
    currentHubName: 'Chicago Central Sort Facility',
    destinationHubId: 'hub_chi_north',
    destinationHubName: 'North Suburbs Distribution Hub',
    assignedAgentId: 'cagent_01',
    assignedAgentName: 'Devonte Reed',
    currentStatus: 'in_transit',
    expectedDeliveryDate: '2026-09-17 14:00',
    codAmount: 0,
    codCollected: false,
    timeline: [
      { timestamp: '2026-09-16 09:30', location: 'Chicago Central Facility', status: 'picked_up', description: 'Consignment collected from sender loading dock', actor: 'Devonte Reed' },
      { timestamp: '2026-09-16 11:15', location: 'Chicago Central Facility', status: 'at_origin_hub', description: 'Inbound scan and dimensional check complete', actor: 'Hub Scanner 04' },
      { timestamp: '2026-09-16 13:00', location: 'Chicago Central Facility', status: 'sorted', description: 'Sorted to Line 2 - North Suburbs Shuttle', actor: 'AutoSort Conveyor' },
      { timestamp: '2026-09-16 14:30', location: 'I-94 Northbound', status: 'in_transit', description: 'Inter-facility transit underway on Line Haul 88', actor: 'Dispatch System' },
    ],
    deliveryAttempts: [],
    createdAt: '2026-09-16 08:45',
    updatedAt: '2026-09-16 14:30',
  },
  {
    id: 'shp_02',
    awbNumber: 'AWB-EXP-88911',
    trackingNumber: 'TRK-88911-US',
    tenantId: 'tenant_apex',
    sender: {
      name: 'Apex Pharma Direct',
      phone: '+1 (312) 555-8833',
      email: 'colddispatch@apexlogistics.com',
      address: '400 N Michigan Ave',
      city: 'Chicago',
      postalCode: '60611',
    },
    receiver: {
      name: 'Dr. Evelyn Martinez',
      phone: '+1 (312) 555-4920',
      email: 'emartinez@chicagoclinic.org',
      address: '676 N St Clair St, Suite 1800',
      city: 'Chicago',
      postalCode: '60611',
    },
    parcel: {
      weightKg: 1.2,
      lengthCm: 20,
      widthCm: 15,
      heightCm: 12,
      declaredValue: 480,
      description: 'Insulated Vaccine Sample Container (2°C-8°C)',
      isFragile: true,
    },
    serviceType: 'same_day',
    currentHubId: 'hub_chi_01',
    currentHubName: 'Chicago Central Sort Facility',
    destinationHubId: 'hub_chi_01',
    destinationHubName: 'Chicago Central Sort Facility',
    assignedAgentId: 'cagent_02',
    assignedAgentName: 'Maya Lin',
    currentStatus: 'out_for_delivery',
    expectedDeliveryDate: '2026-09-16 17:00',
    codAmount: 0,
    codCollected: false,
    timeline: [
      { timestamp: '2026-09-16 10:00', location: 'Chicago Downtown', status: 'picked_up', description: 'Picked up from Apex Pharma Cold Storage', actor: 'Maya Lin' },
      { timestamp: '2026-09-16 11:30', location: 'Central Hub', status: 'sorted', description: 'Priority Same-Day scan verified', actor: 'Hub Admin' },
      { timestamp: '2026-09-16 13:10', location: 'Central Hub', status: 'out_for_delivery', description: 'Assigned to Agent Maya Lin for last-mile delivery', actor: 'Maya Lin' },
    ],
    pod: {
      confirmationMethod: 'otp',
      status: 'pod_pending',
      recipientName: 'Dr. Evelyn Martinez',
      recipientPhone: '+1 (312) 555-4920',
      otpCode: '4920',
    },
    deliveryAttempts: [
      { attemptNumber: 1, timestamp: '2026-09-16 14:15', reason: 'Recipient in surgery, requested delivery retry at 16:30', agentName: 'Maya Lin' }
    ],
    createdAt: '2026-09-16 09:15',
    updatedAt: '2026-09-16 14:15',
  },
  {
    id: 'shp_03',
    awbNumber: 'AWB-EXP-88912',
    trackingNumber: 'TRK-88912-US',
    tenantId: 'tenant_apex',
    sender: {
      name: 'Benchmark Legal Services LLP',
      phone: '+1 (312) 555-7711',
      address: '200 W Madison St, 34th Floor',
      city: 'Chicago',
      postalCode: '60606',
    },
    receiver: {
      name: 'Sarah Jenkins',
      phone: '+1 (312) 555-6321',
      email: 'sjenkins@sterlingequity.com',
      address: '111 S Wacker Dr, Suite 4100',
      city: 'Chicago',
      postalCode: '60606',
    },
    parcel: {
      weightKg: 0.8,
      lengthCm: 30,
      widthCm: 22,
      heightCm: 3,
      declaredValue: 50,
      description: 'Confidential M&A Escrow Documents',
      isFragile: false,
    },
    serviceType: 'same_day',
    currentHubId: 'hub_chi_01',
    currentHubName: 'Chicago Central Sort Facility',
    assignedAgentId: 'cagent_03',
    assignedAgentName: 'Tariq Al-Mansoor',
    currentStatus: 'delivered',
    expectedDeliveryDate: '2026-09-16 12:00',
    actualDeliveryDate: '2026-09-16 11:42',
    codAmount: 0,
    codCollected: false,
    timeline: [
      { timestamp: '2026-09-16 08:30', location: 'West Madison Office', status: 'picked_up', description: 'Documents sealed and collected', actor: 'Tariq Al-Mansoor' },
      { timestamp: '2026-09-16 09:10', location: 'Downtown Hub', status: 'sorted', description: 'Fast-tracked for immediate courier drop', actor: 'Tariq Al-Mansoor' },
      { timestamp: '2026-09-16 10:20', location: 'Downtown Hub', status: 'out_for_delivery', description: 'Out for pedestrian bicycle delivery', actor: 'Tariq Al-Mansoor' },
      { timestamp: '2026-09-16 11:42', location: '111 S Wacker Dr', status: 'delivered', description: 'Delivered and verified via digital signature', actor: 'Tariq Al-Mansoor' },
    ],
    pod: {
      confirmationMethod: 'digital_signature',
      status: 'pod_verified',
      recipientName: 'Sarah Jenkins',
      recipientPhone: '+1 (312) 555-6321',
      signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><path d="M 10 30 Q 50 10 90 30 T 170 30" stroke="%2310b981" stroke-width="3" fill="none"/></svg>',
      deliveryTimestamp: '2026-09-16 11:42',
      agentId: 'cagent_03',
      agentName: 'Tariq Al-Mansoor',
      notes: 'Received at front reception desk with corporate security ID badge verified.',
    },
    deliveryAttempts: [],
    createdAt: '2026-09-16 08:00',
    updatedAt: '2026-09-16 11:42',
  },
  {
    id: 'shp_04',
    awbNumber: 'AWB-EXP-88913',
    trackingNumber: 'TRK-88913-US',
    tenantId: 'tenant_apex',
    sender: {
      name: 'Midwest Hardware Direct',
      phone: '+1 (630) 555-2244',
      address: '550 E North Ave',
      city: 'Carol Stream',
      postalCode: '60188',
    },
    receiver: {
      name: 'Robert Callahan',
      phone: '+1 (312) 555-9011',
      address: '1840 S Michigan Ave, Apt 4B',
      city: 'Chicago',
      postalCode: '60616',
    },
    parcel: {
      weightKg: 8.5,
      lengthCm: 45,
      widthCm: 30,
      heightCm: 25,
      declaredValue: 320,
      description: 'Heavy Tool Set & Replacement Drill Heads',
      isFragile: false,
    },
    serviceType: 'standard_ground',
    currentHubId: 'hub_chi_01',
    currentHubName: 'Chicago Central Sort Facility',
    assignedAgentId: 'cagent_04',
    assignedAgentName: 'Brandon Scott',
    currentStatus: 'delivery_failed',
    expectedDeliveryDate: '2026-09-16 15:00',
    codAmount: 145.50,
    codCollected: false,
    timeline: [
      { timestamp: '2026-09-15 16:00', location: 'Carol Stream Depot', status: 'picked_up', description: 'Shipment received from merchant' },
      { timestamp: '2026-09-16 04:30', location: 'Chicago Central Sort', status: 'at_origin_hub', description: 'Sorted for South Loop delivery sector' },
      { timestamp: '2026-09-16 08:30', location: 'South Loop Route', status: 'out_for_delivery', description: 'Loaded into delivery vehicle' },
      { timestamp: '2026-09-16 13:40', location: '1840 S Michigan Ave', status: 'delivery_failed', description: 'Premises locked. Intercom code unanswered. Delivery rescheduled', actor: 'Brandon Scott' },
    ],
    deliveryAttempts: [
      { attemptNumber: 1, timestamp: '2026-09-16 13:40', reason: 'Building callbox unanswered, customer unreachable by phone', agentName: 'Brandon Scott' }
    ],
    createdAt: '2026-09-15 15:30',
    updatedAt: '2026-09-16 13:40',
  },
  {
    id: 'shp_05',
    awbNumber: 'AWB-EXP-88914',
    trackingNumber: 'TRK-88914-US',
    tenantId: 'tenant_apex',
    sender: {
      name: 'BioGen Diagnostics Lab',
      phone: '+1 (312) 555-8800',
      address: '710 N Lake Shore Dr',
      city: 'Chicago',
      postalCode: '60611',
    },
    receiver: {
      name: 'St. Vincent Pathology Center',
      phone: '+1 (317) 555-0922',
      address: '2001 W 86th St',
      city: 'Indianapolis',
      postalCode: '46260',
    },
    parcel: {
      weightKg: 3.2,
      lengthCm: 28,
      widthCm: 22,
      heightCm: 18,
      declaredValue: 2400,
      description: 'Pathology Blood Assays (Temperature Stabilized)',
      isFragile: true,
    },
    serviceType: 'next_day_express',
    currentHubId: 'hub_chi_01',
    currentHubName: 'Chicago Central Sort Facility',
    destinationHubId: 'hub_ind_01',
    destinationHubName: 'Indianapolis Sorting Center',
    currentStatus: 'sorting_pending',
    expectedDeliveryDate: '2026-09-17 10:30',
    codAmount: 0,
    codCollected: false,
    timeline: [
      { timestamp: '2026-09-16 14:00', location: 'Lake Shore Lab', status: 'picked_up', description: 'Consignment received by courier agent' },
      { timestamp: '2026-09-16 15:10', location: 'Chicago Central Sort Facility', status: 'at_origin_hub', description: 'Unloaded into Inbound sorting bay 3' },
    ],
    deliveryAttempts: [],
    createdAt: '2026-09-16 13:20',
    updatedAt: '2026-09-16 15:10',
  },
];

export const MOCK_MULTI_POINT_PICKUPS: MultiPointPickup[] = [
  {
    id: 'mp_01',
    pickupCode: 'MPP-2026-091',
    tenantId: 'tenant_apex',
    assignedAgentId: 'cagent_01',
    assignedAgentName: 'Devonte Reed',
    destinationHubName: 'Chicago Central Sort Facility',
    totalParcels: 32,
    overallStatus: 'in_progress',
    createdAt: '2026-09-16 07:30',
    stops: [
      {
        id: 'stop_01',
        sequenceNumber: 1,
        locationName: 'MicroCenter Tech Hub',
        address: '2645 N Elston Ave, Chicago',
        contactPerson: 'Alex Rivera',
        contactPhone: '+1 (773) 555-0129',
        timeWindow: '08:00 - 09:00',
        parcelCount: 14,
        status: 'picked_up',
        notes: 'Parcels ready at security bay B',
      },
      {
        id: 'stop_02',
        sequenceNumber: 2,
        locationName: 'Nordstrom Fulfilment Center',
        address: '55 E Grand Ave, Chicago',
        contactPerson: 'Clara Vance',
        contactPhone: '+1 (312) 555-4933',
        timeWindow: '09:30 - 10:30',
        parcelCount: 10,
        status: 'picked_up',
        notes: 'Garment returns and express apparel',
      },
      {
        id: 'stop_03',
        sequenceNumber: 3,
        locationName: 'Boutique Optics Chicago',
        address: '900 N Michigan Ave, Level 3',
        contactPerson: 'Marcus Thorne',
        contactPhone: '+1 (312) 555-8812',
        timeWindow: '11:00 - 12:00',
        parcelCount: 8,
        status: 'pending',
        notes: 'Handheld scanner required for optical serials',
      },
    ],
  },
  {
    id: 'mp_02',
    pickupCode: 'MPP-2026-092',
    tenantId: 'tenant_apex',
    assignedAgentId: 'cagent_04',
    assignedAgentName: 'Brandon Scott',
    destinationHubName: 'South Suburbs Sorting Facility',
    totalParcels: 24,
    overallStatus: 'assigned',
    createdAt: '2026-09-16 11:00',
    stops: [
      {
        id: 'stop_04',
        sequenceNumber: 1,
        locationName: 'Grainger Supply House',
        address: '1001 W Adams St, Chicago',
        contactPerson: 'Tom Novak',
        contactPhone: '+1 (312) 555-7744',
        timeWindow: '13:00 - 14:00',
        parcelCount: 12,
        status: 'assigned',
      },
      {
        id: 'stop_05',
        sequenceNumber: 2,
        locationName: 'Midwest Dental Supplies',
        address: '1600 S Halsted St, Chicago',
        contactPerson: 'Nancy Wu',
        contactPhone: '+1 (312) 555-3399',
        timeWindow: '14:30 - 15:30',
        parcelCount: 12,
        status: 'pending',
      },
    ],
  },
];

export const MOCK_DELIVERY_HUBS: DeliveryHub[] = [
  {
    id: 'hub_chi_01',
    name: 'Chicago Central Sort & Distribution Facility',
    code: 'HUB-ORD-01',
    city: 'Chicago, IL',
    address: '4200 S Pulaski Rd',
    capacityParcels: 25000,
    currentParcelsCount: 18450,
    incomingShipmentsCount: 420,
    pendingSortingCount: 125,
    sortedShipmentsCount: 16800,
    outgoingShipmentsCount: 1525,
    managerName: 'Greg O’Hara',
    status: 'operational',
  },
  {
    id: 'hub_chi_north',
    name: 'North Suburbs Cross-Dock & Last Mile',
    code: 'HUB-NS-02',
    city: 'Skokie, IL',
    address: '7400 N Cicero Ave',
    capacityParcels: 10000,
    currentParcelsCount: 8900,
    incomingShipmentsCount: 180,
    pendingSortingCount: 88,
    sortedShipmentsCount: 7900,
    outgoingShipmentsCount: 912,
    managerName: 'Samantha Lin',
    status: 'high_volume',
  },
  {
    id: 'hub_mke_01',
    name: 'Milwaukee Regional Consolidation Hub',
    code: 'HUB-MKE-01',
    city: 'Milwaukee, WI',
    address: '500 W Canal St',
    capacityParcels: 15000,
    currentParcelsCount: 7200,
    incomingShipmentsCount: 95,
    pendingSortingCount: 22,
    sortedShipmentsCount: 6800,
    outgoingShipmentsCount: 378,
    managerName: 'Klaus Mueller',
    status: 'operational',
  },
  {
    id: 'hub_ind_01',
    name: 'Indianapolis Crossroads Sorting Hub',
    code: 'HUB-IND-01',
    city: 'Indianapolis, IN',
    address: '2751 S High School Rd',
    capacityParcels: 20000,
    currentParcelsCount: 11400,
    incomingShipmentsCount: 210,
    pendingSortingCount: 45,
    sortedShipmentsCount: 10200,
    outgoingShipmentsCount: 955,
    managerName: 'Patricia Adams',
    status: 'operational',
  },
];

export const MOCK_SORTING_RECORDS: SortingRecord[] = [
  {
    id: 'sort_01',
    awbNumber: 'AWB-EXP-88910',
    sourceHub: 'Chicago Central Sort & Distribution Facility',
    destinationHub: 'North Suburbs Cross-Dock & Last Mile',
    sortingCategory: 'Air Express',
    status: 'sorted',
    scannedAt: '2026-09-16 13:00',
    scannedBy: 'Conveyor Scan Station 4',
  },
  {
    id: 'sort_02',
    awbNumber: 'AWB-EXP-88911',
    sourceHub: 'Chicago Central Sort & Distribution Facility',
    destinationHub: 'Chicago Central Sort & Distribution Facility',
    sortingCategory: 'Local Delivery',
    status: 'dispatched',
    scannedAt: '2026-09-16 11:30',
    scannedBy: 'Maya Lin',
  },
  {
    id: 'sort_03',
    awbNumber: 'AWB-EXP-88914',
    sourceHub: 'Chicago Central Sort & Distribution Facility',
    destinationHub: 'Indianapolis Crossroads Sorting Hub',
    sortingCategory: 'Surface South',
    status: 'sorting_pending',
    scannedAt: '2026-09-16 15:10',
    scannedBy: 'Inbound Dock Scanner',
  },
  {
    id: 'sort_04',
    awbNumber: 'AWB-EXP-88919',
    sourceHub: 'Chicago Central Sort & Distribution Facility',
    destinationHub: 'Milwaukee Regional Consolidation Hub',
    sortingCategory: 'Surface North',
    status: 'sorting',
    scannedAt: '2026-09-16 15:25',
    scannedBy: 'Station 1 Operator',
  },
  {
    id: 'sort_05',
    awbNumber: 'AWB-EXP-88925',
    sourceHub: 'North Suburbs Cross-Dock & Last Mile',
    destinationHub: 'Chicago Central Sort & Distribution Facility',
    sortingCategory: 'Exception',
    status: 'exception',
    scannedAt: '2026-09-16 14:50',
    scannedBy: 'Quality Audit station (Weight mismatch)',
  },
];

export const MOCK_COURIER_AGENTS: CourierAgent[] = [
  {
    id: 'cagent_01',
    name: 'Devonte Reed',
    phone: '+1 (312) 555-8910',
    email: 'devonte.reed@omnicore.io',
    assignedZone: 'Zone 4 - West Side & Industrial Loop',
    status: 'out_for_delivery',
    assignedDeliveriesCount: 28,
    completedDeliveriesCount: 22,
    failedDeliveriesCount: 0,
    commissionEarnedTotal: 1840,
    expensesTotal: 210,
    pendingPayoutAmount: 480,
    paidAmountTotal: 1570,
    vehicleType: 'van',
  },
  {
    id: 'cagent_02',
    name: 'Maya Lin',
    phone: '+1 (312) 555-4920',
    email: 'maya.lin@omnicore.io',
    assignedZone: 'Zone 2 - Near North & Streeterville',
    status: 'out_for_delivery',
    assignedDeliveriesCount: 34,
    completedDeliveriesCount: 29,
    failedDeliveriesCount: 1,
    commissionEarnedTotal: 2150,
    expensesTotal: 140,
    pendingPayoutAmount: 520,
    paidAmountTotal: 1770,
    vehicleType: 'motorcycle',
  },
  {
    id: 'cagent_03',
    name: 'Tariq Al-Mansoor',
    phone: '+1 (312) 555-6321',
    email: 'tariq.m@omnicore.io',
    assignedZone: 'Zone 1 - Central Loop Financial District',
    status: 'available',
    assignedDeliveriesCount: 42,
    completedDeliveriesCount: 42,
    failedDeliveriesCount: 0,
    commissionEarnedTotal: 2680,
    expensesTotal: 45,
    pendingPayoutAmount: 640,
    paidAmountTotal: 2085,
    vehicleType: 'e_bike',
  },
  {
    id: 'cagent_04',
    name: 'Brandon Scott',
    phone: '+1 (312) 555-9011',
    email: 'brandon.s@omnicore.io',
    assignedZone: 'Zone 5 - South Loop & Bronzeville',
    status: 'out_for_delivery',
    assignedDeliveriesCount: 19,
    completedDeliveriesCount: 14,
    failedDeliveriesCount: 1,
    commissionEarnedTotal: 1320,
    expensesTotal: 180,
    pendingPayoutAmount: 310,
    paidAmountTotal: 1190,
    vehicleType: 'van',
  },
];

export const MOCK_AGENT_COMMISSIONS: AgentCommission[] = [
  { id: 'comm_01', agentId: 'cagent_01', agentName: 'Devonte Reed', awbNumber: 'AWB-EXP-88910', deliveryDate: '2026-09-16', basePay: 15, commission: 8.50, bonus: 5.00, totalPayable: 28.50 },
  { id: 'comm_02', agentId: 'cagent_02', agentName: 'Maya Lin', awbNumber: 'AWB-EXP-88911', deliveryDate: '2026-09-16', basePay: 12, commission: 12.00, bonus: 6.00, totalPayable: 30.00 },
  { id: 'comm_03', agentId: 'cagent_03', agentName: 'Tariq Al-Mansoor', awbNumber: 'AWB-EXP-88912', deliveryDate: '2026-09-16', basePay: 10, commission: 15.00, bonus: 10.00, totalPayable: 35.00 },
  { id: 'comm_04', agentId: 'cagent_03', agentName: 'Tariq Al-Mansoor', awbNumber: 'AWB-EXP-88890', deliveryDate: '2026-09-15', basePay: 10, commission: 10.00, bonus: 0, totalPayable: 20.00 },
  { id: 'comm_05', agentId: 'cagent_04', agentName: 'Brandon Scott', awbNumber: 'AWB-EXP-88894', deliveryDate: '2026-09-15', basePay: 14, commission: 9.00, bonus: 0, totalPayable: 23.00 },
];

export const MOCK_AGENT_PAYOUTS: AgentPayout[] = [
  {
    id: 'pay_01',
    payoutReference: 'PAY-2026-09-01',
    agentId: 'cagent_03',
    agentName: 'Tariq Al-Mansoor',
    periodStart: '2026-09-01',
    periodEnd: '2026-09-15',
    grossEarnings: 1480,
    commission: 560,
    expenses: 45,
    adjustments: 0,
    netPayable: 2085,
    status: 'paid',
    requestedAt: '2026-09-15 18:00',
    processedAt: '2026-09-16 09:30',
  },
  {
    id: 'pay_02',
    payoutReference: 'PAY-2026-09-02',
    agentId: 'cagent_02',
    agentName: 'Maya Lin',
    periodStart: '2026-09-01',
    periodEnd: '2026-09-15',
    grossEarnings: 1250,
    commission: 420,
    expenses: 100,
    adjustments: 0,
    netPayable: 1770,
    status: 'approved',
    requestedAt: '2026-09-15 19:15',
  },
  {
    id: 'pay_03',
    payoutReference: 'PAY-2026-09-03',
    agentId: 'cagent_01',
    agentName: 'Devonte Reed',
    periodStart: '2026-09-01',
    periodEnd: '2026-09-15',
    grossEarnings: 1100,
    commission: 360,
    expenses: 110,
    adjustments: 0,
    netPayable: 1570,
    status: 'pending',
    requestedAt: '2026-09-16 08:20',
  },
];

// ============================================================
// SCHOOL & CORPORATE EMPLOYEE SHUTTLE MOCK DATA
// ============================================================
export const MOCK_SHUTTLE_ROUTES: ShuttleRoute[] = [
  {
    id: 'route_sh_01',
    routeCode: 'S-CORP-101',
    name: 'Tech District Corporate Campus Express',
    organizationType: 'corporate_it',
    destinationCampus: 'OmniCore Innovation Campus, West Loop',
    totalDistanceKm: 28.5,
    estimatedDurationMins: 45,
    assignedBusNumber: 'BUS-SH-104',
    assignedDriverName: 'Arthur Vance',
    status: 'active',
    stops: [
      { id: 'stop_s1', name: 'Lincoln Park Metro Station', sequence: 1, scheduledTime: '07:30', address: '2000 N Halsted St', passengersAssignedCount: 14 },
      { id: 'stop_s2', name: 'Old Town Square', sequence: 2, scheduledTime: '07:45', address: '1200 N Wells St', passengersAssignedCount: 11 },
      { id: 'stop_s3', name: 'River North Tech Center', sequence: 3, scheduledTime: '08:00', address: '350 W Ontario St', passengersAssignedCount: 16 },
      { id: 'stop_s4', name: 'West Loop Campus Gate 2', sequence: 4, scheduledTime: '08:15', address: '900 W Fulton Market', passengersAssignedCount: 0 },
    ],
  },
  {
    id: 'route_sh_02',
    routeCode: 'S-SCH-204',
    name: 'Oakridge International Preparatory Academy Line A',
    organizationType: 'school',
    destinationCampus: 'Oakridge Academy Main Campus, Evanston',
    totalDistanceKm: 22.0,
    estimatedDurationMins: 40,
    assignedBusNumber: 'BUS-SCH-012',
    assignedDriverName: 'Gregory Scott',
    status: 'active',
    stops: [
      { id: 'stop_s5', name: 'Edgewater Plaza', sequence: 1, scheduledTime: '07:15', address: '5400 N Sheridan Rd', passengersAssignedCount: 12 },
      { id: 'stop_s6', name: 'Rogers Park Community Center', sequence: 2, scheduledTime: '07:30', address: '1500 W Morse Ave', passengersAssignedCount: 15 },
      { id: 'stop_s7', name: 'South Evanston Gate', sequence: 3, scheduledTime: '07:45', address: '300 Main St, Evanston', passengersAssignedCount: 9 },
      { id: 'stop_s8', name: 'Oakridge Preparatory Campus Dropoff', sequence: 4, scheduledTime: '08:00', address: '1200 Ridge Ave, Evanston', passengersAssignedCount: 0 },
    ],
  },
  {
    id: 'route_sh_03',
    routeCode: 'S-HOSP-301',
    name: 'Northwestern Memorial Hospital Night Shift Shuttle',
    organizationType: 'healthcare',
    destinationCampus: 'Northwestern Memorial Clinical Pavilion',
    totalDistanceKm: 34.0,
    estimatedDurationMins: 50,
    assignedBusNumber: 'BUS-MED-044',
    assignedDriverName: 'Frankie Moreno',
    status: 'scheduled',
    stops: [
      { id: 'stop_s9', name: 'South Loop Transit Center', sequence: 1, scheduledTime: '18:30', address: '1100 S State St', passengersAssignedCount: 8 },
      { id: 'stop_s10', name: 'Pilsen Health Center', sequence: 2, scheduledTime: '18:50', address: '1800 S Blue Island Ave', passengersAssignedCount: 12 },
      { id: 'stop_s11', name: 'UIC Medical District Station', sequence: 3, scheduledTime: '19:05', address: '900 S Paulina St', passengersAssignedCount: 14 },
      { id: 'stop_s12', name: 'Northwestern Memorial Hospital Hub', sequence: 4, scheduledTime: '19:25', address: '251 E Huron St', passengersAssignedCount: 0 },
    ],
  },
];

export const MOCK_SHUTTLE_SCHEDULES: ShuttleSchedule[] = [
  {
    id: 'sch_01',
    routeId: 'route_sh_01',
    routeName: 'Tech District Corporate Campus Express',
    shift: 'morning_inbound',
    departureTime: '07:30',
    arrivalTime: '08:15',
    busReg: 'BUS-SH-104',
    driverName: 'Arthur Vance',
    driverPhone: '+1 (312) 555-3321',
    occupancyCount: 38,
    capacityTotal: 45,
    status: 'in_transit',
  },
  {
    id: 'sch_02',
    routeId: 'route_sh_01',
    routeName: 'Tech District Corporate Campus Express',
    shift: 'evening_outbound',
    departureTime: '17:30',
    arrivalTime: '18:15',
    busReg: 'BUS-SH-104',
    driverName: 'Arthur Vance',
    driverPhone: '+1 (312) 555-3321',
    occupancyCount: 41,
    capacityTotal: 45,
    status: 'scheduled',
  },
  {
    id: 'sch_03',
    routeId: 'route_sh_02',
    routeName: 'Oakridge International Preparatory Academy Line A',
    shift: 'morning_inbound',
    departureTime: '07:15',
    arrivalTime: '08:00',
    busReg: 'BUS-SCH-012',
    driverName: 'Gregory Scott',
    driverPhone: '+1 (847) 555-8844',
    occupancyCount: 36,
    capacityTotal: 40,
    status: 'arrived',
  },
  {
    id: 'sch_04',
    routeId: 'route_sh_03',
    routeName: 'Northwestern Memorial Hospital Night Shift Shuttle',
    shift: 'night_shift',
    departureTime: '18:30',
    arrivalTime: '19:25',
    busReg: 'BUS-MED-044',
    driverName: 'Frankie Moreno',
    driverPhone: '+1 (312) 555-9923',
    occupancyCount: 34,
    capacityTotal: 42,
    status: 'scheduled',
  },
];

export const MOCK_SHUTTLE_PASSENGERS: ShuttlePassenger[] = [
  {
    id: 'pax_01',
    name: 'Sarah Connor',
    employeeOrStudentId: 'EMP-CORP-4821',
    type: 'employee',
    assignedRouteId: 'route_sh_01',
    assignedStopName: 'Lincoln Park Metro Station',
    contactPhone: '+1 (312) 555-9011',
    emergencyContact: 'John Connor (+1 312 555-9012)',
    hasBoardedToday: true,
    boardingTimestamp: '07:32',
  },
  {
    id: 'pax_02',
    name: 'Liam Neeson',
    employeeOrStudentId: 'EMP-CORP-4822',
    type: 'employee',
    assignedRouteId: 'route_sh_01',
    assignedStopName: 'Old Town Square',
    contactPhone: '+1 (312) 555-7744',
    emergencyContact: 'Mary Neeson (+1 312 555-7745)',
    hasBoardedToday: true,
    boardingTimestamp: '07:47',
  },
  {
    id: 'pax_03',
    name: 'Zoe Saldana',
    employeeOrStudentId: 'EMP-CORP-4823',
    type: 'employee',
    assignedRouteId: 'route_sh_01',
    assignedStopName: 'River North Tech Center',
    contactPhone: '+1 (312) 555-3399',
    emergencyContact: 'Marco Perego (+1 312 555-3398)',
    hasBoardedToday: false,
  },
  {
    id: 'pax_04',
    name: 'Lucas Davenport',
    employeeOrStudentId: 'STU-OAK-904',
    type: 'student',
    assignedRouteId: 'route_sh_02',
    assignedStopName: 'Edgewater Plaza',
    contactPhone: '+1 (773) 555-1288',
    emergencyContact: 'Parent: Dr. Weather Davenport (+1 773 555-1289)',
    hasBoardedToday: true,
    boardingTimestamp: '07:16',
  },
  {
    id: 'pax_05',
    name: 'Emma Watson',
    employeeOrStudentId: 'STU-OAK-905',
    type: 'student',
    assignedRouteId: 'route_sh_02',
    assignedStopName: 'Rogers Park Community Center',
    contactPhone: '+1 (773) 555-8933',
    emergencyContact: 'Parent: Chris Watson (+1 773 555-8934)',
    hasBoardedToday: true,
    boardingTimestamp: '07:31',
  },
  {
    id: 'pax_06',
    name: 'Nurse Jacqueline Vance',
    employeeOrStudentId: 'MED-NMH-1022',
    type: 'employee',
    assignedRouteId: 'route_sh_03',
    assignedStopName: 'South Loop Transit Center',
    contactPhone: '+1 (312) 555-6611',
    emergencyContact: 'Dr. Robert Vance (+1 312 555-6612)',
    hasBoardedToday: false,
  },
];

// ============================================================
// WAREHOUSE EXTENSIONS: CROSS-DOCKING & CONSOLIDATION MOCK DATA
// ============================================================
export const MOCK_CROSS_DOCK_RECORDS: CrossDockRecord[] = [
  {
    id: 'cd_01',
    inboundShipmentRef: 'INB-TRUCK-8891',
    origin: 'Detroit Automotive DC',
    destination: 'Midwest Regional Assembly, Milwaukee',
    receivedAt: '2026-09-16 06:45',
    sortingStatus: 'sorted',
    consolidationGroupRef: 'GRP-MIL-CONSOL-01',
    outboundDispatchRef: 'OUT-HAUL-902',
    dispatchStatus: 'consolidated',
  },
  {
    id: 'cd_02',
    inboundShipmentRef: 'INB-TRAIN-4421',
    origin: 'Long Beach Port Terminal, CA',
    destination: 'Chicago Central Logistics Yard',
    receivedAt: '2026-09-16 09:10',
    sortingStatus: 'pending',
    dispatchStatus: 'waiting_consolidation',
  },
  {
    id: 'cd_03',
    inboundShipmentRef: 'INB-REEFER-1102',
    origin: 'Grand Rapids Cold Depot',
    destination: 'St. Louis Distribution Hub',
    receivedAt: '2026-09-16 11:30',
    sortingStatus: 'repackaged',
    consolidationGroupRef: 'GRP-STL-COLD-02',
    outboundDispatchRef: 'OUT-REEF-301',
    dispatchStatus: 'dispatched',
  },
  {
    id: 'cd_04',
    inboundShipmentRef: 'INB-EXP-5590',
    origin: 'O’Hare Cargo Terminal 5',
    destination: 'North Suburbs Fast Track',
    receivedAt: '2026-09-16 13:15',
    sortingStatus: 'sorted',
    consolidationGroupRef: 'GRP-ORD-SUBURB-03',
    dispatchStatus: 'waiting_consolidation',
  },
];

export const MOCK_CONSOLIDATION_GROUPS: ShipmentConsolidationGroup[] = [
  {
    id: 'cgrp_01',
    groupCode: 'GRP-MIL-CONSOL-01',
    destinationHub: 'Milwaukee Regional Consolidation Hub',
    totalShipments: 18,
    totalWeightKg: 14850,
    masterSealNumber: 'SEAL-MIDWEST-9941',
    assignedVehicleReg: 'IL-6102-FR',
    status: 'sealed',
    shipmentIds: ['cd_01', 'shp_01', 'shp_04'],
  },
  {
    id: 'cgrp_02',
    groupCode: 'GRP-STL-COLD-02',
    destinationHub: 'St. Louis Distribution Hub',
    totalShipments: 12,
    totalWeightKg: 9400,
    masterSealNumber: 'SEAL-COLD-8822',
    assignedVehicleReg: 'IL-9428-TX',
    status: 'dispatched',
    shipmentIds: ['cd_03', 'shp_05'],
  },
  {
    id: 'cgrp_03',
    groupCode: 'GRP-ORD-SUBURB-03',
    destinationHub: 'North Suburbs Cross-Dock & Last Mile',
    totalShipments: 8,
    totalWeightKg: 3200,
    status: 'open',
    shipmentIds: ['cd_04'],
  },
];

// ============================================================
// SOCIAL MEDIA & DIGITAL PROMOTION MOCK DATA
// ============================================================
export const MOCK_SOCIAL_POSTS: SocialPost[] = [
  {
    id: 'soc_01',
    channel: 'LinkedIn',
    campaignName: 'Cold Chain Compliance & Pharma Safety 2026',
    caption: 'Maintaining -20°C integrity from manufacturer to clinical trials. How Apex Global Cold Chain eliminates thermal breach risks with real-time IoT telematics. #Logistics #ColdChain #PharmaSupply',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    scheduledTime: '2026-09-17 09:00',
    reach: 18450,
    engagements: 1240,
    leadsGenerated: 34,
    conversions: 6,
    spend: 450,
    status: 'published',
  },
  {
    id: 'soc_02',
    channel: 'Instagram',
    campaignName: 'Express Parcel Delivery Same Day Launch',
    caption: 'Need it delivered today? Our high-speed urban sorting hubs and zero-emission couriers guarantee doorstep delivery in under 4 hours across the city! ⚡📦 #ExpressDelivery #CityLogistics',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    scheduledTime: '2026-09-18 11:30',
    reach: 42300,
    engagements: 3820,
    leadsGenerated: 88,
    conversions: 24,
    spend: 600,
    status: 'published',
  },
  {
    id: 'soc_03',
    channel: 'Google',
    campaignName: 'B2B Dedicated Heavy Haulage Search Ads',
    caption: 'High-intent search campaign targeting Midwest industrial manufacturers and ODC machinery transport tenders.',
    scheduledTime: '2026-09-16 00:00',
    reach: 12900,
    engagements: 980,
    leadsGenerated: 42,
    conversions: 8,
    spend: 1250,
    status: 'published',
  },
  {
    id: 'soc_04',
    channel: 'Facebook',
    campaignName: 'Corporate Employee Commute Pooling Promo',
    caption: 'Transform employee daily commutes with dedicated corporate shuttles. Reduce carbon footprints, eliminate parking stress, and boost punctuality with GPS-tracked employee transit.',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop&q=80',
    scheduledTime: '2026-09-20 14:00',
    reach: 0,
    engagements: 0,
    leadsGenerated: 0,
    conversions: 0,
    spend: 200,
    status: 'scheduled',
  },
];

// ============================================================
// TENANT PUBLIC CMS CONFIGURATION MOCK DATA
// ============================================================
export const MOCK_TENANT_CMS: Record<string, TenantPublicCms> = {
  'apex-global': {
    tenantSlug: 'apex-global',
    companyName: 'Apex Global Logistics & Cold Chain',
    tagline: 'Enterprise Cold Chain Telematics, FTL Freight & Express Services',
    logoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=100&auto=format&fit=crop&q=80',
    primaryColor: '#059669',
    accentColor: '#10b981',
    contactEmail: 'bookings@apexlogistics.com',
    contactPhone: '+1 (800) 555-APEX',
    address: '400 N Michigan Ave, Suite 1200, Chicago, IL 60611',
    heroHeadline: 'Mission-Critical Logistics & Precision Cold Chain Transport',
    heroSubtitle: 'From temperature-monitored biopharma haulage to high-speed express consignments, Apex Global connects enterprises across North America with certified reliability.',
    enabledServices: [
      { id: 'cold_chain', title: 'Pharma & Food Cold Chain', description: 'Certified -20°C to 8°C continuous thermal telemetry with live sensor alarms and GDP compliance.', icon: 'Snowflake' },
      { id: 'freight_ftl', title: 'Full Truckload (FTL) Freight', description: 'High-capacity inter-state dedicated haulage with electronic weighbridge verification and e-Way bills.', icon: 'Truck' },
      { id: 'courier_express', title: 'Express Parcel Delivery', description: 'Real-time AWB tracking, multi-point pickups, and digital proof-of-delivery confirmation.', icon: 'PackageCheck' },
      { id: 'corporate_shuttle', title: 'Executive & Campus Shuttles', description: 'Scheduled group transit with live GPS vehicle tracking and digital QR boarding passes.', icon: 'Users' },
    ],
    promotions: [
      { code: 'APEXEXPRESS20', discountText: '20% Off First Express Consignment', validity: 'Expires Oct 31, 2026' },
      { code: 'COLDCHAIN15', discountText: '15% Off Pharmaceutical Trial Transit', validity: 'Expires Dec 31, 2026' },
    ],
    faqs: [
      { question: 'How can I track my shipment in real time?', answer: 'Enter your authoritative AWB tracking number (e.g. AWB-EXP-88910) in our online tracking portal to view live timeline events, hub scans, and estimated arrival windows.' },
      { question: 'What proof of delivery is provided upon receipt?', answer: 'We support instant digital signature capture, SMS OTP verification, and photographic delivery receipts sent immediately to sender and receiver.' },
      { question: 'Can we book multi-point pickups for business shipments?', answer: 'Yes, enterprise accounts can configure sequenced multi-stop pickups with pre-assigned time windows directly from their client portal.' },
    ],
  },
  'speedyjet': {
    tenantSlug: 'speedyjet',
    companyName: 'SpeedyJet Express Delivery Services',
    tagline: 'Lightning Fast Urban Delivery, AWB Tracking & Local Hubs',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    primaryColor: '#2563eb',
    accentColor: '#3b82f6',
    contactEmail: 'help@speedyjet.com',
    contactPhone: '+1 (888) 555-JET1',
    address: '100 Peachtree St NW, Atlanta, GA 30303',
    heroHeadline: 'Same-Day City Delivery & Express Parcel Logistics',
    heroSubtitle: 'Guaranteed 4-hour urban delivery, high-density sorting hubs, and transparent doorstep tracking.',
    enabledServices: [
      { id: 'same_day_courier', title: 'Urban Same-Day Express', description: 'Doorstep pickup and delivery in under 4 hours across major metro zones.', icon: 'Zap' },
      { id: 'multi_point', title: 'Multi-Stop Merchant Pickup', description: 'Consolidated commercial parcel collections for retail and e-commerce warehouses.', icon: 'Layers' },
      { id: 'cod_service', title: 'Cash on Delivery (COD)', description: 'Secure payment collection and automated merchant reconciliation upon delivery.', icon: 'CreditCard' },
    ],
    promotions: [
      { code: 'SPEEDYJET10', discountText: '$10 Off Any Same-Day Booking', validity: 'Valid this month' },
    ],
    faqs: [
      { question: 'What is the cutoff time for same-day express?', answer: 'Orders placed before 2:00 PM local time are dispatched and delivered same-day by 7:00 PM.' },
      { question: 'Do you require signature confirmation?', answer: 'All packages over $100 declared value mandate OTP code verification or digital signature on glass.' },
    ],
  },
  'horizon-shuttle': {
    tenantSlug: 'horizon-shuttle',
    companyName: 'Horizon Campus & Corporate Transit',
    tagline: 'Reliable Scheduled Commutes for Schools, Tech Parks & Universities',
    primaryColor: '#4f46e5',
    accentColor: '#6366f1',
    contactEmail: 'shuttles@horizonshuttle.com',
    contactPhone: '+1 (800) 555-RIDE',
    address: '401 Terry Ave N, Seattle, WA 98109',
    heroHeadline: 'Smart Scheduled Mobility for Corporate & Campus Communities',
    heroSubtitle: 'Fixed-route passenger shuttles, student bus tracking, and corporate shift synchronization with real-time seat availability.',
    enabledServices: [
      { id: 'corporate_transit', title: 'Corporate Tech Campus Shuttles', description: 'Daily employee commuter routes connecting transit hubs to business campuses.', icon: 'Briefcase' },
      { id: 'school_pooling', title: 'School Bus Roster & Tracking', description: 'Safe, geofenced student transport with parent arrival notifications and boarding logs.', icon: 'BookOpen' },
    ],
    promotions: [
      { code: 'HORIZONSHIFT', discountText: 'First Month Free for Corporate Pilot Routes', validity: 'New Enterprise Accounts' },
    ],
    faqs: [
      { question: 'How do passengers board the shuttle?', answer: 'Passengers present their digital QR pass or employee badge at boarding for automated driver scanner verification.' },
    ],
  },
};

// ============================================================
// SUPER ADMIN CUSTOM FEATURE OVERRIDES
// ============================================================
export const MOCK_TENANT_FEATURE_OVERRIDES: Record<string, TenantCustomFeatureOverride[]> = {
  'tenant_apex': [
    { featureKey: 'courier_express', name: 'Courier & Express Delivery Module', description: 'AWB management, sorting hubs, multi-point pickups, and agent commissions.', source: 'vertical', isEnabled: true, enabledBy: 'system', enabledAt: '2026-09-10' },
    { featureKey: 'corporate_shuttle', name: 'School & Corporate Shuttle Module', description: 'Fixed routes, sequential stops, schedules, passenger rosters, attendance.', source: 'vertical', isEnabled: true, enabledBy: 'system', enabledAt: '2026-09-10' },
    { featureKey: 'cross_docking', name: 'Warehouse Cross-Docking Workspace', description: 'High-velocity inbound-to-outbound sorting and shipment staging.', source: 'custom_provision', isEnabled: true, enabledBy: 'admin@omnicore.io', enabledAt: '2026-09-12' },
    { featureKey: 'shipment_consolidation', name: 'Multi-Day Shipment Consolidation', description: 'Consolidation group packing, weight tallying, and master seal generation.', source: 'custom_provision', isEnabled: true, enabledBy: 'admin@omnicore.io', enabledAt: '2026-09-12' },
    { featureKey: 'social_promotions', name: 'Social Media & Digital Promotions', description: 'Integrated multi-channel campaign planning for Instagram, LinkedIn, Facebook, and Google.', source: 'addon', isEnabled: true, enabledBy: 'sarang@apexlogistics.com', enabledAt: '2026-09-14' },
    { featureKey: 'public_portal', name: 'Tenant Public Mini-Website & Booking Portal', description: 'Vertical-tailored public web portal with live AWB lookup and instant quote booking.', source: 'package', isEnabled: true, enabledBy: 'system', enabledAt: '2026-09-01' },
    { featureKey: 'ai_predictive_maintenance', name: 'AI Predictive Component Telemetry', description: 'Deep learning failure prediction on transmission and brake wear.', source: 'enterprise_override', isEnabled: true, enabledBy: 'admin@omnicore.io', enabledAt: '2026-09-15' },
  ],
};
